// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get cluster-level utilization aggregates for the latest completed report
	// (GET /cluster_rightsizing)
	GetLatestRightsizingClusters(c *gin.Context, params GetLatestRightsizingClustersParams)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /cluster_rightsizing/{report_id})
	GetRightsizingReportClusters(c *gin.Context, reportId string, params GetRightsizingReportClustersParams)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetLatestRightsizingClusters operation middleware
func (siw *ServerInterfaceWrapper) GetLatestRightsizingClusters(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestRightsizingClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestRightsizingClusters(c, params)
}

// GetRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportClusters(c, reportId, params)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/cluster_rightsizing", wrapper.GetLatestRightsizingClusters)
	router.GET(options.BaseURL+"/cluster_rightsizing/:report_id", wrapper.GetRightsizingReportClusters)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLcOJLgqyDqdqKlWOrTds/YG/4hS7ZbMS5bp6++uLbPgyJRVViRAAcAS67uc8S+",
	"w13EPtC+yT7JBRIACZLgR+nD7tnrPzNuFQgkEolEfudvk5hnOWeEKTl58dtExkuSYfjn0YIwNeUJOSd/",
	"L4hU+m+54DkRihIYkfGE6P8nrMgmL36ZxJwxEiuSTKJJQmX1n5+iiVrnZPJiIpWgbDGJJl92OM7pTswT",
	"siBsh3xRAu8ovICJZ5QletiLiSB/L6ggScQZ4fOX5ZSoNv/Xr1+jcqiGBCCrVuWzfyWxmnyNzKYuFFaF",
	"bO8n5kzylHy2E1PO9F8TImNBc/Ofk+NCCMIUsmNRNRZJM21U4qMGYzTpwcfXaEKE4CKwXjU/jED+z4Fp",
	"3JnUZ7nEYkEU0j+iORdILQnCGhUetJudnv5qZ4UFw5lG3i8+ZjXRHHuzNX46qU0ePLoodBbB88zzlMZY",
	"//6OSnVOZM6ZJO2zxdVA+G+qSAb/+CdB5pMXk/+2V12EPXsL9rzZP6yIWFFyqxe1UGAh8HrShL+20ADI",
	"5aQtcGvH91v7mDXagz+ssmNeMOX9RpkiCyLMj3fa+/V0cNcATzSpE6eDxSw8gIvraRsLNNlk8w2QqCY9",
	"GBpa+RVh8TLD4ua8YAFOIAhWJDkCPM65yLCavJgkWJEdRWGnLaASKm8u6K/k7SyM+6QQsM8LEtcn5cUs",
	"9WZkRTYzX3RwhNfABjIiJV4QROdILalEVBEzP5pjmsK1a4Fo0FmuTJn68Wk1zoO1nCy8lYyoJU/akJU4",
	"RWYEKiRJ0BbZXexGaJV9ZljRFdkOgZZjKt530XQuSH5SR1+DvdGMIJlrvsyZfhpuEJygRgdmCRKYJTxD",
	"c5qmaKvC1AHiLF1reEachiRSUs5Ox+JQ8kLE5AQrLBUX4Y0pYMsDY5aCF4tlXqjpLJejSCd0ESrwPWS3",
	"oWzD5FNDjcrrJN0CNPIuUegCHuMcz2hK1brzOXYj7H83H+s0JbEyN6SPkX3ILfjVinr9ORckxlKRu05A",
	"mczvDkDjjKrd+BPXoGwjsTmHj68gytNCz/SGYFWIEE4TIV8zPNPsA+7YHBepmryY41SSqHHnfl4StSQC",
	"nZxfoK0Tqgl2VmjJ7JwYokIX8ZIkRUrENqISETOxFT+oRLGBpiLfGecpwQyYpQBJoQbF5D1nzTfmxUQv",
	"jwvFM3OlaxJOtYKTcd4UabpGR2Y8MMkzLBTFzb9OMStwOonMmiFxTV8OvCAnd8DYhfkUMLcZYr52H+qV",
	"oin9tWTaLcF2ThPC4oBoqG86ivmKAEzVSJQTEROm9F+39ncO9ve3IxTjNC5SjSSEJVodn13t3BK6WOo/",
	"uDmC7DTDX2imz+Bgfz+aZJSZ/9oPMNo4Lz7j1aIN6ZGF8fjsChXVdgOAPgQIGf7SBmFq5vhGIOTPn7VB",
	"eP5MLd16NP0W2MhI1n8gGcm4WH8DKHrP5JtBMepYvgE0TfZv701FOxUhV4dYbaFCaeQziODD4V6nC4WF",
	"8uwBdRzAr8g+ZZSzXXQsSKIRglOJsCCIw1CcarE1F2RFeSHTNQJJI0EritHZ1SXai6vPdrW80hALYiIC",
	"q5+9nu4QFvOEJOj4COlBdK6VC4JmBUtSEpY7pbzlIiDMro4JU0SgcoR3Vt7f2g/DDc0vUxnAzg3N0eW7",
	"ixpkKyLMP2vqvPcSFiLthu3q/J0PViFoCKJCEuFUpvA85YgooFP1UkNQcBuluNwuiTOZwCsI3wQfWreI",
	"e8QFwcm6sqcYi4SjOviPHAtZ+zM86maJcdaMxh7N/57bhYM/HvvQdIzwQAyOOCvh7psANhMc8NrssMkZ",
	"LAqDNxtk9LeCF3mnma9hi6gf6gd3oxd6joZ1KsNf3hG2UMvJi2f7+3c2AvKMKpLlah1l+MvLZ/v7QJdz",
	"mlrhvQ7RG/g7Il9yYXQetHWrFb8ZQSucUq3EJ9t14A72D58aXlv+5f4Wy4yylwcAMUwPMIev4VuDOirz",
	"FK+RvYg18B4VuP22/dTCYFHcQTiWRXdxgSHOZUR074GYkZSzBVL8oZlYNIGDb3/qJPK48UzZ98jpEYKo",
	"QjCSaKh3w2K5jzy9cQ9gt3oIizXVv3HrqLw5Ddu/5oIQrUvGVK3fvgrbaJZYJLdYkKM4JqnWP0ky5Svf",
	"xOA9Mksu1WkAP6eAlTklAvE5oEKP1KxbEKOrJG4DmodjpbDW+SbRhBVpqtWayQslCtJhp047rD1c8Zin",
	"l/BDyCLCFU6H9q+6vl4RlpjXqd98CL+2F2thv5wxckfWjfzG5hwWeinjhChM02HrSOPkmN6VpDHi83nK",
	"cYL88eY0a8c3w5IkiDNkdoNkkedcKGP+yWTdzZOvd+y0mvXo/55EE5FkGhkrngYV5rr5OAL4AYWzkeZQ",
	"jffRgxnGJ2RF4xBu3h8doQR+RLQkcFne9hInP0g0w/ENZQv07uq99FExuLtO+7y1GxzpgaErd0IEXWne",
	"I3iGPEhPT7TAPKdfdtEFzuApK7SWgZlEUv8hX64ljXGK7AoIYNlFRzNJmILdvX9zAebQlOtx5T7l7qTb",
	"wDHtvKd2wHV5nxri7vHFaUlM8JGzBL9/fXl0dhahs6vz1xE6eXsctAi7C9y2VhiC1b+jrevpm4tIbyxC",
	"19c8jdCHy59en28HBdnAA2cvuUeLJZ31XsozTEX7Smrm2CMhvb74H9QwUL06UhzllAHJzUrDueK76HSO",
	"tMSjSBIhbD6IeZZxpj+ZcbX0jk6zXUmMVFjawWKcpuvgoYZf0CtJxE5C5lS/cQBbaYvK9UZD1NG2bjeO",
	"39gAKwbT9TQHbOBB3+XQTOEDHrZvB8+ZpESRd3hG0rcpn2l09ngW53MjlLcZDbAjzWyvpxKpJVZoiRM4",
	"8VTPjQTJ+Mr31XgPGIwIYKP8GOa7xbI9SwdKSkDd5KGtv5aKZliRc8wWpMPTQuwYwzMzuhBYazXo4PKV",
	"3qw+qZbWPiNSHWMZutLWi9DgEh8nh8+yp/vy4yTIHsiXvAPr3fP9mD193jXfLRebA/g8OzgMTxjSm99Y",
	"W74WmEMODfr82Tt+S4Tz89ShgJ/QjBcs0Uh+/uxPvrFWE45Ygcl6xOuol7rK866l4KcHWsrRyhkRB5ev",
	"hlwlder7ClrQaLdXNNHP4UbDE7rZB3ST0b0+TYmzPCU9vnqpkoSs7urz81183kqfesiSiJIpyk5bgKcp",
	"DZ3ldQx6mWcC7L8WROhXtTs2R+9CkeS8YLKP1ZYDK5e4DDLY8VYqjUwwVZFeS1X4+a9effCGOymzevK3",
	"tKa4I3MSa0E0QVzAQ77jnvW7+ctfrRWRl1p5CTBx/Wc00yO0SFHkoCAkBXA3/TG2DG8rFwSkx9pv+l+A",
	"jZr9utsTXoJzBQuFeDb8bAEhCZIczbEIQDRuwTGud9hAwIhMxI533LdULSlD2DsuUTDPoZgTY1oxu8TW",
	"GiMKxpz90VJjaX/U0ibTauHYwKrQ/dD/S87KtbuHeEB1Djovoe0ccuxto3PQa7u/7lnKjY+NfdCEGr7w",
	"hoarK47yFDMWlKV6WOOI6AdDKFGDAfmw9TPVpsuk5ZmNIaIwXgc9W0hTfpqSFJiQRFvWxYwOIiT1pMBZ",
	"t4PX4J68uhnS1BCKqLxBkv6q5QH09hXwNY+nlWDub/dHGPXy8mpC/6DBKUNFtciz8BqAsdHxbnXdzjz2",
	"p+bDg4HgN7PQIBkE37USyA4+lAu+EETKihdzlq7Nu2TZzLZvmejbYvClDRgvOnjjBRErGpOdlKxIahjk",
	"LvqgoVG33Py3ROQLlQr957/9XwRuGrRFk5Rs60fNQou2vFNl5f62d9HPek8+q51TRuWSSP01lcjxzQge",
	"UGmgscZZeMhgxV2POztPkePHmzJcn0naqcI/uvlDnpewigk2/4HAw7bqJRXOcnP4GgfG56J1QPtdTSbv",
	"jVa8s0+nbY0e74fJbxZ7Zjg6uXin6ZZ8Ael08mJiHeYfi/39J+Ql+svbV2CrssEw6CX6IRc8+aE7rrGh",
	"wzD698JhqDLzoa2rq9OTmuBSFDQZbysJ+mra3oo8udMxpljLiebjkWfZGfXa676BbfRHTANU4/mnIegA",
	"N8lxyJDg4uj1r8gqMWEmvqi0pJAIwMrXQg8Ni/qqTw6uJrA7HpQgqnEwr92iD2snygfQPRrJlK0IU1ys",
	"h744LQf+Qx3F9VSiDKt4qV+M8o78IJGl6eie0e3XVKgCp1OsVyCD4e3mcMwSmx67FvzeE3XLxU3It64f",
	"sYAMhDPifG7MfFz6LJikCTFI0XOjDxdBppgHvEJnCCcJiBNYSrpgJNHvpgkg1wLgHMdBfpbhQNT19OjY",
	"mw5JQhiarQcBYxUuGnu2+wQLNNg1cy60Ij9iUuMbcQ7yrpnNKJTCMLQlixkjCmVYgihyfHpyjhhXIGc2",
	"ddsnh2G+0Drvn6hUfCFwZsDItbgAdkrjCG0cP1a4RrNdjsyKnWaUXeO0IF1WI5KHfmkm2bhJ7BeRgSRE",
	"vz/xoN6SF8dckF7p/fjsCsUwqNMf7GsreXHB4xuiBueUdtiYWXtEA08oKN0dYMIJ0T8IJ9NX7ck0elyw",
	"H2Vo+ipkohiGs9sdPtZfXXqhu33Kp2wucOAsjYglz4wF0KiCG1JlnBcfVkQc8yyjKiOhN0IfnR4Tl2PQ",
	"ub5qu+i4FlUM3BUdpSmHiwNRxhLtIfNEnDk357GlrBGG2Mpdtrk2GNqsppIzfmtUAOsEShJqhOazGm47",
	"MVedip5tPGBwHTtg0idow8HDzGcTNgMkPXSm50dTR/x3OVr7qTtb+594ham5LqNO174n41HoHuPArk20",
	"h70PYRx2iDTVzelCsB71kzvroPTyYMfXDGWplm4Tr4fA2k0JMxCbmdJlzeiwHJTfIWdNu5+G3oCjpqAH",
	"fyv182iyShKQPXCafphPXvwyICcmyY13o79uoOGf+iJ6mOP2cY5RQr2mupY6P5niHDwhVnUGtBk5j1CB",
	"StXBOWpbkK+qJ2AjKOx3n0OP7umJE2dtvF4wTM9OsCJCBi0T1+aHxlQI53QXveECWXMC+jj5y+7+7pPd",
	"/Y+TQY3ZgzqqTqb3RE+s2BY8VT+9qg99zWysr+XqjVyeEZP4X4B2aB/6/uPTg8Yf97U9t0rT6h09lW1M",
	"g/ZkgAvhd2oiCTg7lbIIRVpISaR0L1GLeuJuZ2pHInEZY9FPIWZY5K/vVgtto1vZW8lbquLlZhndLhDK",
	"sUypMEuwsGn6Lu1O/5ebPpoUzMbvdRQbWKWYdQSXrjLZ6ZUOh0h25liHEh/byQJ++lwoONcG4/oxuku8",
	"IkgW8zmNKVguBF3RlNRsDl54a0alpGxxVo1q27aN+zVGq4scolurKU2gDRYE2Xk2CARsIMztNYSsM0xF",
	"H5764z3fECzpLCVluKfJwJaVamN8XTvGweXiuh4ptrM/8uFBEqPv59QbTJWtn8ZjhUP8LnxU53SxVJL+",
	"StnCvib9dmFfeBkFdXuBxnPVJB9j+AmKEZcQjq9/RqcnVQwzGM/xYiHIAhSLueDZ4MNfLTPw7rc3MIid",
	"e+Pk++FgJAr6E47NmCD4jsNO+TmZO0nOTnrMs7zQsrxNIYdQO/RxkvAMU7YTHxw++TjZDoa2uiXDbpsT",
	"z2Hj1nTyccPU6IRKt3YueFJAPuOO/aIThJ4064ur6ZaxZPzHv3vRdH/aRnuo/G17t5FTndSSs7f2//Pf",
	"/s/B/j760/YuOtVA5oKoWo5pjAtlkyrBvZTy292PbGRUYFfidR12M6oBOHh8S7BxR6b21p+2x4MSTPb9",
	"2S0hiyzDYg3OBiJ2rqcow19MVLxEW5IQZLNgEeONSKX+ZYPZvTUMrCB/tnVyPaBpMCxoGk+MK4SR1ukd",
	"De7c0oTAsK3bJY2X6JYXaYLsTUWKZmQHp8Zgb+L55Pboc02ovAlvKRd8RbVCRZK/vtJb00PLjdV+7Thh",
	"qLVypyPuzCpvLD0FwOzoEGzTLtgCKdgbQbcxAZr1HoAOO7PMh1f3SO2uq4O56LOH4c9xXoRk5iLT66+M",
	"nb9gSiIcCy4lwmkKHjyb3tAqaNE0i9UW0yT1+WbWuZ431pDflqbOoZXvtG+D08/ZOGDOj6ZoazoClpDx",
	"73Mc9qzWcwhuqVrWCBoeCFggVDikS3HznufGw+mBEt2rogAwndqT2ElY/ZjvI5EhScXkSHdK7zOs4uVn",
	"SX+tF5r58WnUewg5Eei/F0Ssz4iYI8ELluwoQfNwEF6PJGQkIJPJxecId0lBiiMZ85yYoocrItZWOPHE",
	"omCU8ENEAMKCn63Fp7/AzekcHrWohBPQldIVMelsVvKDDCeYoAzh245QIY1PW3+CUxM8ZlV/e4FM2lpp",
	"vjTvX1vbd/kJJcotyH8+3N+POmTRJdVLUTO/+VzL1pQhSWLOEom2nuzvv0zwOkIHf9nff3lLyE2E9JQv",
	"M87UMhyBmHJ+M8PxzeclL4RsQhO1MjzMaHRLWcJv9erwXRXo+OfDffQSPdlHCV7L8JL6Fn8eCMnSKJ5Z",
	"WVgWs9LS3q8q+MQ0cPGmRAkad+S52Od5ZBJFipW9u2PeTfNij8nNMK/rqJHPR440gtnneKT1rDY8KtFi",
	"YDPrmh2VSBjA+jkoMZspY2OUMOA9fn2qssAL2oKyDOglvHVOh+5iRVor/Yw3KKnocrw+NzHb0oe5IJD2",
	"iGzxHCckl+kW9kptuRuJ9sqL3hGgHAocuKq8GEZjDAbe1PlP4LGv7O3dxRG8ZJEayoNuk+xOxpjrqaWY",
	"gAnG4OszYcn447LfSIXF6EMORS86/ER1OaU2fQ3COs676MZFb3mUOOpC9VvDDB2E8vWoVJpYrKXGCOyU",
	"yF10JQl6+/oS7Ylqqb3faPIVzntegNiIMuChkJu96cEauC+MitDp5h4OwrPPr9vioFjpDYQFRqHXgdmO",
	"LahGOiRmRGFj6qJqyQvl46kHrRAargQlKyNiAIrtlJTFaZHoNTyE/8E//7/in/8lmd14Nle+A+0C7+ZK",
	"3DVMoUMiDAVBZXyzWs/R5BYLRtkiFC3I2Y65V2WE/fUUrON/L4igJEGzwmTiM+5L/na3oFPv3t3J5+o3",
	"cTgeh0IP4NBxXEHM/x91uB6uDpcH7O+wEFcYOluJq4M6egKKoJZ/ozR1V17LXVIHmpyr/CUql+6maqij",
	"cT3tTirHSeCxgJIZHOHEL5gBtcFG3ss7nEVCVyQqN2p2ndmqWUHozM8egNbp9u1ADJGLi9QZV0+//SqF",
	"jvJ6elKmKtQnvaEs5KRc52DUWplEC5e8YGtnxIngWYTmKc/zdYQKOYuQJILiNCozXkdW1bienlj/RsO4",
	"FzJZvyqkLRxk4JCxpBGiCYmQxApHiK2ycIF6VyKoIxPW/YwoM4n14zLV5zQNJaFjtbTxeuh6evJXpIc5",
	"K1jiBzY0obwh68549xuydjHva5NVQ6UxoNssd1iunhczIgeiq+UIoAXKcVtc50RIKhVhKkKUJSQnTEPz",
	"uevvjLPqp+CZiCTrDhsySS0SYXSOb5EhXjTFeQ45qAkVJFbo3dV7hOOYSF/o9myJcolFX2xShUMqkRmM",
	"ZkTdEsJQVqSK5ilYNEfW8r6emkfTPOZyfDeTFuoVZbFCCVG2MlQ13oSDblTMLK4FRAdXqsWabjY5ZzER",
	"7BgrsuAiGNxUrWLGorgafIel4D0as0xqBm6yRFIPA+86l3LUxggLe3Jc7LZburnXEJqj4VY119OOSEx7",
	"AOtQkviKCM0I3RCn8FE90y66YjeM3/pHaELrcJ6bZLQfPuib9YOfxn0sKGink2jysxGiIc7bsCYj4R4l",
	"KyqNQOLKUMA8IwPK7UYtdtbego1fqvUbP9TBafzoQdf4xQHb+LOFfShR29SGJIkv7tfwbRyGle6mSVuR",
	"L8p0RSExzzLCkmaRnECAbOOQl1woK/GYX2YuTxOWHVR9XURtSUf1jYZp0dByT+gV+KBHuVAJjpcW/i2o",
	"nshFYiKBzJ03xRNrCeq/PIueRIefvJsaKM3ek1CTDnEdu7IpB6JSECUKSWoweMFIpjTJwpaZcQRbg69X",
	"ccmxUkRoCD5+vJhEG/KdtOIrgPTwib0/PQ4IoSwhX0I5Ign54oj3/elxr1QSsDflq6dHJhk1lPe6elqm",
	"qrrap3qNRujX9fRWM6NLzlMZzqld/di3yI8Pschgrq1LfrCStUbyJmm252ROBFRysyKmyy8uAQaDmWu0",
	"FyrHHJZdnMHzlSD4JuG3gbjApZ8c25vmVg70zdUd4SNvuDCpAybHcty4n6la/uzZkLq/ec9V//ShdKtJ",
	"ELZBQLpWDd+vzjppX6halz157NNxFwueqwB0SYnw/AltDuYWclx2tnZ1ITlDFUwIasdEiDBB4yVJDDc2",
	"aYFJWVEoJ8IM3EUXhdYBSEJAzC6XebU+LufcDaUw+fnJ/Wkqbaq1IXPVCnr33xyDNohIf7/jIVBBrWKw",
	"btu0eFthETpEsgVltrvIJX0VoYP9nUPzr8P9nWfmX8/2//mSvtquhU9UiDM7t36CO2Lu7at7fOyQ9cAI",
	"D270cp0TeZ+F9AQDiwRpdrOU4XYm6D0vINraf3lVpQhF6ODlayzXETp8OSUJLbIIPXn5ExZJhJ6+/HlJ",
	"FXmb8lrnvs4t5sXQ4YX2N/IyHJ9dwQVAswJKAFSlWPd3nn6c6H882/mL+cfznYMfzb8O/rzz5ND888nh",
	"P9fKtXZtYwrhZ4+4E7PA8GZCe3iy86P9/cdnOweHdr8Hh893Dp/Z4YfPfhy30fc0Lm/7Q25ztgZJAqRD",
	"b2MWVAuk3Y/5v6ddAJdk7L/Wo1zijXzCUJl2b/t34FfMf6PPCZabNJcdho7L+/KJFjK51IrqXVme/TrE",
	"6fIHq4cgcHbnB2RIUhwlJm4sI+phF2D8O6HyRo4sBL4iCCuUEiwV4ow486ENnN1ExqwJmKXk4zBZvsn+",
	"414/sA5KDt29oCDajh0NWIzu2LULnPjQJmvtbAzOz99oprWLpoXWiNI1Il/itJB0ZQ0gtidXO2lncwcM",
	"nITfNSzUFOwRevXAup29xaB0oom97eswBlbqG5rnJNHIkgpSUWYESaJAGxQFQTjlbAElpsyZQXIF0GzM",
	"sxllZiZXdvHp/r6t3Gh7FrxAdO6+pBJh034CAuC9Vuk3NJcAag28rRmOb26xSCSILFhRk3+5/S/1SSEW",
	"XFNMY1ozGTEzF9LQiwbcw4fejcUjYoQkFQqY2n2UFmybn7he8Wuj6dHj0NRQ66KSqD/pe14vhtF2ua1V",
	"yHxfnRYWM5ymmzjIsiSQBZMlz5A0+ReaAMqy0Xb+YIhkV0WJyyWpCs25cPDjFNLK3UeDFSTKcRrcIIc0",
	"I9zb26j8R5WpsRMISKCm9wdV6OKnI6P2KY5mBU2TWhP/dgVK+nb0tBaPV6ebLNCJUej273BnExVWh7v7",
	"u/vbG2CyQkp9L0Hs1s2DfTm5jZJUntcqWCW1Vg6r3YnG8+H0tYTvirRM/BrK4cph7RtRleVsVwyUVRVL",
	"Y82DtEgVLzd0lIWC9+pIttkRPbVcbBdrytmxdT0NJThVXzgPnAQfhUi8uvkmFL50Jif+V4LIIlVh83A5",
	"qipd1CtfZqfNL/Qs4KMZ3IceJdEc+meUIYgjbNhdLoJafx7rJqjmnU4eyeZ/1+iUZkSTKyYWsGobLXjT",
	"K5DVpPjGzdIiDLUW8kwLC9VoQNr08noXvYHsI66WRNxSSTqqhljZ97UWJpNNOny7u0elkUQT19CrnDO4",
	"YjgorXHxOvsokSxPg9W32ijByI0ehwov4/DziF7iZasYkLW8sFS0h4Lhqug//h1pWhmVplkDpitPvJl5",
	"jhXk5W79aftfnEgKwaGMt9Ip7wZFMF03AAXkeD8KFOE075NAgvYjLN7dnbudhP2oZ9GZOh0G5GGPwz6H",
	"F+EqeE5lMK1FXFSUVsNJ8oFV/5zPIyQLCXFQyehWdiaa3AegquhRk2Q8uaTkzLWnbVjE6uxJ2SVovQ+U",
	"3Yg5U5gyp9R3vY+18hqsepFJsP+4qpap1EIXkVWWi2NJYMkfTPlXtFX6Pm0ia/lfXORLzMy/EGUmcIzO",
	"0o6IQS6IPCPCVLUdVSgXPF/Or2vK3I4LwYvz4mg+pywYoOgykcoOkXq90xMZwAEo15TZutD6udQCUVKk",
	"jbJXI0AKVIgdWTzcIQDqbeCyWKgLiLxDhGKfHO+TpheXtTF1Jl3tRh364YltxMNWPXM7tzeunLmLzg2F",
	"pIVtkg6sEiA97OHA0Y9RABiQni55SgRmMXk9VPvNxkq8gezn8jOQq8ynETL1UjJM4by0bAMJ53KJE37b",
	"JO85XFypMFNojmnKV77y4kk8cyoyvXQorcH8YuKIfUdsY62tGeXQuoTMaZBBzHmahCiyFaBRVew0n2xO",
	"nFA6/TQYZQ97adXCrqqt1+KlxZKkf/n841Moar/dudL7oCD7pkjTWgEmswQ3VQLZAsm1VCTbNF5m4RXY",
	"l92130EsXbhWjoEi+gPrjmuC4Rf776jSPOLAq55xrtV2iFFXXcaCrejCh/ATl6p9BoO736TnSoCYmsCP",
	"tBxsoqWfg/Jv1PS8M0jrTFCom+N1QrgvIkDb7+av1hpgmq+Wcfd35audvsL/4raDUOn9owx0Rz4vC4f3",
	"ywqa7DKywCHzc1dqQ4+loVL2WwvFWAudVtsnCdpSVgVnHLlQTUsY279r20OobN7wa8OIVCT56XrweTcD",
	"nQji9C3/dddHeqtvzXKdEwFR1Cbxqqjx8C6Y/A3aRNZ+KcjFQpbdUFAM7qiHkovenx4HC6aWztie9jzQ",
	"AFj6Ok5T4uhQJqGdf7c+WbZyv5KhwzLiuesqL3NACmeyyDpFn82SoLotVz1XrGbFQgLbcZghjARZFCkW",
	"Y6hCabZuy8NXluFeYRReAoiRLSO1XWs7G67c16gGFuxa6VSLpmnquk3rQSZowFt4C2Z4z5UdDP3w7J/s",
	"RuwfPqTupw83wWMvxtcZv868ep9G/YenFpJMQ4LAiggJrviiJRSUrYeqYpsbtTXzLkvbKOApmi0V3HtM",
	"nFpk+cKwyaO/Csg/cGOt79NQ6w6NtOormNTizpTiTcShLUHyFMeueaVGjPlluyf34tEzLu4qQTGuZilm",
	"NyFRKixVBDkud9JDKVC0hIgSNbVYM8dc7xRaE0ws8IR860oMqVC2PaqxakklilgVwqQgZzsl2DsmJZKu",
	"CErpTGDo2tRyO7ZLwHj5bndJkqrn3RK3ULjVFHQeH07UdgNrWVQGlk8DaHS60qCTt+lbDWDGoWw0owgc",
	"Z4hb9G6gq//M+J7uw+3cvYMImZkT+wiG8pK70BvEZ2ujsl8O9Oi12U2n6kYe7kBedh53zchHZke2MN/o",
	"P94xoGos3jHAbyveNaQCuWOESaHsaMxTHWP4TgSkmlCP7u/r8ewszN3yL7pC4ZvU2d6owqLncN2snvad",
	"61SfPHyF6ZArcFPM6ck3q01ZeUg3qwA9ZnRX9aThIs6VF8rUN/cLGtftRAG5dUzV5rNQueZxOB5Zivks",
	"UIO5q8pyRzmp5tNqaje58QE8dgEXRspQKWXvGg7VVfboLlRk+VNHplMzI6rF5EAUh1GvRoWrXb6qyEPR",
	"sSW2V9nxmDLXrqC1nXhMLLwFvVriU0/O16NgAX6wLZEeDhUdyQKwmEsytosOoMktGNV2+ak3SSSQYN/R",
	"d9bkkrmMqUZtsgtkfzcJTzkR6Jwk6Ces0F+PLxAWisYpQU8Pnzx99vzAE2hs4DY8/6bB6eeqsRXINlnB",
	"qFrX/qplBIrTz0vMkjTYVLACmPh80494yhcCJ+S8ViIhpHbY30mCPlwg+5WLM0NeGy7wpEEsurEN26Fg",
	"UMTIHzZciNkeY6jFlzvEr6YLHByiogo67B9JGzJZZh4hE6t7dHY68QJ6J6sDoIKcMJzTyYvJk9393Seg",
	"n6slEMKeiQp+8dtkYSIbuOv0dZpMXkzeEgUTWykdBGIwnMDHh/v7VqpSdhKvDsnev0qDZ6MuDCkT/jKw",
	"51AosizjN5+ZpZtCudbKcYokESsirEIA6RaOTegdmUhob7Lc+vLqe7+we5/yhEzMuRGpXvFk/bCb1vM7",
	"60cjjF+r41+/H9I1ZCheYrYgicbT0zDSoQYgEm4LetzzgITL2Tylhi3d+fSOARh7gFCtSv++1yyi1EnL",
	"/rjHxGv1Zc3aGMCxc1v4WzCpTqVtDxow3gNpsESogFTpeEacIdfmcc9VL/WK73o4bWcmtrD8DoSadp8p",
	"kLWwwBkxRZV+6agzeXLxrlZr0nZvqqqqopfoB69hwg8fJ9u76ENGla0PXAhWK8MLJUD1An8vCNhWjOw4",
	"ma1fl8toLlyebbuQZZOPf3pE6hlo4xYgIpf9UNODXP8waa7k01B5VVTaFJBoF2mGuPd7c1vXGMnkq4dB",
	"bCYFeGDZwuYdlLn3W9n37OtmVNoqXz2WSgPVrK+uTk8cjemntSIxvytbna/79NaSEv64Gd/3ZhiKgITC",
	"b3wJMJKugWmA9OXeb9Vhf91ruP26nr1An78BGq939gv37kNcoAVhxARGuFjg05MmWe7gJ/M/zw7jg+Qp",
	"+cvz/YNDUx0gcFlqdbO7b0vlfflfWw6kjx+Tf/7fbsFf9nee4535p98Ofvy6/U+T702jm9In1MUHH02Y",
	"I7b4z6Bs5jEIq8/e60mAOISyTqS7I1qLruC5121xew4gZ7b2SM3eDVMS3rkLNOwBaV7x/Lgc2Dr/pyGB",
	"tSzuLxXPc3I/LqAB8KvXf42676uD8/HVruZSIRJ1Qx5K/YoDE3aoYAoLVT+1h1fCfBQItZEmdvgdzsF6",
	"i8BacH+drJzSNeqiDOWCLyDm8n7kjqEnh4t39ikfLm29xER1bZsPccZXxHTgs01MXO6H30a85Jaad86w",
	"JFqwqdPSCazgV7YYxQS8RQyM9+MCBopAJ3SPHzQxYMoztD6peqhsXZ2/Q5yl6+1d9J6sTKl+LglUFxMm",
	"4k8gVwBgF10uITAvyTllCiWcSODigrhq/jXc4gWmTKqy59skIEz3ovUBuVW5TM81qRBUsZfOt87bp0Hw",
	"vblb+5w8LlcEDvjaIl32YT1ChMVinStrHIBicprQE3RD1hEkQsHKst5jz90HhE04BTYREz50RO2iI+ge",
	"p7kFU+js6hLxFRG3gipiPssFWdlmxG3SbVPEWdGiiIfn26E+h9/WfLYZOcqqWUZ1XEBvh/sH3w0m21ym",
	"AVG/NOl9zgUqmCA4XkJatgsCvKegJEiIy7cejr1a839f+6/tdkniG1lWBMkFXdGULJy+laaoJF6Jtkrh",
	"JHLhGfqfcy5IjLXUuW2r0QSuAbqgbJESk7Xklov16hGEi0MozmKAfx77W3pM2nXrrHvopBzjQlhzIips",
	"fUPGCmdY4rSEANUIAMhDv3xCdRLDa/hZIklSYw6FBxT6eknNI48vrqFHg0Q5jm/wwvQsxeh/np4hLOIl",
	"XREoZWpmmafkC9V0b5q6mkk1XJqy+HyeUkYQZjhdSwqM+fWXmKSgPRVSaZGF8xD/NFCeer1ZerX1Y55l",
	"eEcSPUjvKbU2ZbstiAAE7c21H30B/H1Fye32LjpaYZrichey+jGCzCUZleaiqOpZISO0ymTkwuwjX0mL",
	"XIz5jrs3Uc3sHNnKJpEXAeVHIU5KAMz6JsQ0ZKcCiCd9prTNVP1faV6/QqX7d0YZhpWbC7RujUcqfnpf",
	"RVmaOOyDSBKLdI/pjr7eHQFzFRqpZdiwxAtUmIL9Y4pAt3d16s9lSldUF/q+IN8JnmGuYa4RpNCUeoh+",
	"56pyqnmKjQMEKgMAA6lYfZ9eorV5Ixo5F8qMsHiZYXGzi46MLrXjWVIKZrojQGyrWFWtkLsVFr3EmwqY",
	"R1Q+q1W634JXbnvIhR5Cnx/oxWIMy8YDDjvvexlKPPmJj/d6GwCeat5BTcpme5TgmwBSEKtzInZyTEWp",
	"A7vg0OCr3cLbI77XY87IxZVWJFzqHjWMnfE0DQ2qzDCtMFn92mG5ZnGFZ0308M4xUC8zLbWVzwPSWJS7",
	"qCZqmngJrYcC/cPrqCcw5QYRnft6RllrTr+/DBEsUkpKxhm6Llioxn15eKWjdgzfzVq02YUday3yZLbI",
	"6SpQi1xfusiYEKhAKc2oQuRLTEjiZg3Ylo6YKZNQu+/OyvQQ995YmLxrX+feLeUgTNu2xau01Qe00MZx",
	"gjKiljwxPHtOMNQGMVU0nHfG1KzdUVgsiGoSPjKqORSyZAlk7ZmoKadm4QUxnUmQ4jlP+WKNEiLoyqV4",
	"Qj4PFzcpnasdq5PAXXAt89F7XukYvt1AEOQIMaCYc+ndkTNMRUvfePg7U1tm/YihLqOyFurQBBIWutUg",
	"auu66CPuvE0nJSU8jPfQEqi5e219xyf4RtXefmNTqWDbtLuVVvM0eZalV6EipyQCLa3xyJ1Wly7tPSm+",
	"Sl3dDeh+l2GGFySDLnHX0ypMGdIdIRoyTuG/tnfRtV9TlrN0DWH5TXrXiJZ4FST4wqP337lNasBwBIeD",
	"od+1PQYP/RoNC4GZejD7zdP9Jw+tjchiPqexKcjaoqAIZVRKyhYv0C/lHdo9soUALiBZuZ7UtFsqyLvH",
	"YMX6FEz+MbOelQvVoPpl0rHWpJmm2Fqtli843HNpUKM5KtRSH4uldlnE5oWFHsdwD1Mc38jQ8d+LwcAd",
	"WwfdKpriciIAhZy1OU5lDeh+YJ3UXY0d98LZet/2rbTPqAYorqxStGrVVn8+3x8duT6lVbqyvOOjWZP0",
	"T6otP7aEWS3lvZnf5I0sV7bl4UY8ki6O0SOJe8cs4tIy5c/aoEGQt/Z+YzgjX/s0dqMmmoeskkkbITfw",
	"yM5MlYxddGlI1L1pGseUFaQKm6SuFpgR+jQZSUXT1LpZhnR6LYoM2fb0GFO0A0sHZ2U9ANG+dPMGg2ps",
	"3sv44LNP91Rcmvn0VLzv6vxe5keWWQIuR/DTnYxUZ0ZGsnOMMkIIV2jBqTdVPMteqa7MKaNyeV8btrFT",
	"YCSNm8BIkQ1qFgXr9mQ4VkpZQlc0KXDqa1fKSVy7yLWQT9e2KIAp0ZA7WhrgcecFGxurC4Ytf+oOQ21J",
	"Bg9nq70jbyv14vOCbcLYaiTzAMytOV+AEPZ+s1GtXUFNJpqgdnCD0asFQ13BqgNxd4MFYAIHGIqtLJgf",
	"StEfwGKg7QzTLNgDaVk2LgPXj6V1KpphDd/P2KhsCRjWqFQ0drGddTPBD9JfzqSR7yJX2KwM0HCx0Ven",
	"SHGtIUEhp8qIrWhW9o4jYyyVcvyjozhaENXYyPAdv89r8/A2U7PnwN2+XApeLJZ54e+wkyinRpNAbp+o",
	"xOG9g0ZUGBBNfVWXgGC4oOYlb82QcRzbNhWwQg7airEkO5RJwiSF2BBZzMzpmAyU7c4Q8UF+HrXpqiyf",
	"g7YOdqB/rClkFaanRX3+smzaQVS17D0IpUt2Z2La7RszzoL0LG3rKgeWP9yPJhn+Yte35WG6oXlMEoej",
	"H5tjZElpiOkakcFLNHgAST5NvdXDwZ5Gq4YNPVakZ7XCRlbIg4c9rtARwQ8uGGdsXKer5UrrByfXTOEv",
	"2/cTVgEShBEjt+bkfG40UjBxZ9nLlszO7yuSQPWyMYH+ASnCQPCA0Z0WX90B3t8fMS0OeQHR/ZSkSRlh",
	"KGwwS9n0US/9Asv440RrS2WCxws9U1T9uL2Lri09wnRgosUZiZBf1L6MKjFGX81tI1v+M7IVNSMU58WV",
	"xAtixth/CpzZf8V5cbRawGdHK4is8gx7DjosY4s2AFSrluRLnvKkrHcVjCzhQtW4//ieO1KtweCpz2DS",
	"/wjOQetc2FZs3/IdhO3c6Rn8vm9d3zvnLjJ47A0V29zZp933/uFyvODaa8Hq9MQsTpV0AORalGrzAlP7",
	"7nfCJx/+wfW2950y3Ace3AIAfMAH99EJzaDUf5LLMNWh9KdTP9ju0TB+6sDpDk24nkokILHDmuv/XhBT",
	"Czt4CEdVaoqx7Zn4W6xIJ8ZLIExiw4NEG/C8ighGhCkqSLrue+WbmBi44Kdz2/eTMlOuseyGeH1y8lcv",
	"2+Nvtr7H3yL0tyx59rdtUwfPlk3c9eNp4MtbLBGDtBA3Y1far135Okluwg+OrVfdrLLyqGx/BEFVx/1A",
	"KWo0MGFPilrjZt2NkQZiruot8ZyRv1HKp+7139Q7HU1W2WkiN5FwWtWI9PfhwjXfLiRqPJU8ZAJdRXgP",
	"H9nknb0WE8v6HCVttgI+ggTqIj5KUP9hoyDsY20841LOizRdd57gK5ygBqHf3UPu0uKCqYemEY19ghsn",
	"tNKctCczvzwUzXIfP4i00fY3cEecCRtK27qi1+UXrT69tp45PDMKi92P7NTWs9d/sSkUED9kejMTVn4b",
	"IYye7j9FbrMQDmwDiXc/dieX6D08oNAOgLYy9FpBRLWD6r02WZEqmmOh9rTQvQOB5T3+0TkNdaRwCLVN",
	"kIezEOosGSa9G0f+lsR2BaTg3efe27xJgamnB09C/Z5SYuNWJfrx6fSVCWW9pzgOW6idl+UBLnmn9/qP",
	"zPBpyYZlQ+fTMhagvEhbx7bjekpcJSlW4NQLrTF3cLtLDNQfHZnJNxMDu+rWVCsr3qxbT6VRZn6QAcNz",
	"GD4Yb6qEPJ5jiTPyYQ5H0S92uBPUmx/Whb3xn7pz/P04qB4dxyFVc8MyVuahyjPUYdAkHS4I1nZHtSor",
	"Peqb1lptrDekXd1EPoyjo2PisHh2KehiQYRfNaaqlPA44ll7re+UxtA6OlfNtb/6hTIoI8m/WIFBjq2D",
	"4z0hdz5me2C1U86IEjSWrSIXw4XKhsuSDQZ0PE4Jsk/f8soGJdGOMkffolqXX4SrXQMJ3lStfUBTfnP0",
	"veddVu/ajG3+UZDuj4J0v9uCdEOkXitUtxHDOy5bXf/uqP6PsnjfuSze6Pvx6CXqfMga18QtC66NjutT",
	"lujuvhjXdshjquhmCagRH/LTmJ/9NIvOatqrjrF7tvVY5y6nYwPXZuvaUwMqJAEHq3mRTZ0imzRcjay1",
	"/pqQL/nBwz8xf0RT/BFN8Y8WTdHTFLFHaS7jKUY4y71Lfe+CoNXyVvwGnqDffshRqw7d8Zw9M2KH54NV",
	"4a+n0rCYD/mjV4a/ntaW6kO5ZXtuA/dFYQINEWPlrGxmXrTCaWElvdLDpNFXtV3sRts7M+ZR0WXWGEOa",
	"5QYt6PdWAtO0OaeWHwpJEI4FlzKEsL3f4P9HBEfCxt6mfIbTdND+ewmFgGckNWpTxlfEiheghcqw4Gha",
	"CPbJjPdqc/mo7CmApF4iAOS4oJKFQ+sQqzI4fZg4fhv8aaasHc5Q/BcAP0IQqlFBxhM6X3/Hg3+scDGH",
	"jc0jxkIk4dWKK6sx+Q5ktGVPqXQvY8UzGmvy2d4sPiCglnzwauPoNSpNZItx21pFogwn5H7h2lMgBksc",
	"YJXSkolc0hxt4STZsyzDEc8ekOf1VG5X/Ou3AT0dOsf1kmezr3dyp1DFb8lk6hC7ZOeAIlTfWVJ1zQ67",
	"qOvDH85o40Jb8YwXCmG0ygZ5y3c9tkcILelpHX1XRnE93Sy0ZOzlv54+bMynKZZS+dO9i7vnFVLskTxM",
	"Ne3r6RvBs1rMWoNAfue3tt0++P5BpsGIUc27G9cjxsyEsgznmXexAWQXsX77Eq4704c51iaksGkviMyu",
	"UyObkQ1Erqcb9A5pgGFspXeMW/+2ZBVoIRwkrLpZcuAxeM8DzT2ADPymrA9pjpwJgm8SftsyTOp14FOY",
	"y5xdIdLJi8kezune6mDy9dPX/xcAAP//i2JjukgeAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
