// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get cluster-level utilization aggregates for the latest completed report
	// (GET /cluster_rightsizing)
	GetLatestRightsizingClusters(c *gin.Context, params GetLatestRightsizingClustersParams)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /cluster_rightsizing/{report_id})
	GetRightsizingReportClusters(c *gin.Context, reportId string, params GetRightsizingReportClustersParams)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetLatestRightsizingClusters operation middleware
func (siw *ServerInterfaceWrapper) GetLatestRightsizingClusters(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestRightsizingClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestRightsizingClusters(c, params)
}

// GetRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportClusters(c, reportId, params)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/cluster_rightsizing", wrapper.GetLatestRightsizingClusters)
	router.GET(options.BaseURL+"/cluster_rightsizing/:report_id", wrapper.GetRightsizingReportClusters)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963LcOJIo/CqI+naipVjq5kvPtDf8Q5Zst2Jdtj7d+ouv7eNBkagqrEiAA4Al1/Rx",
	"xL7DORH7QPsm+yQnkABIkAQvJZXsnj39p9t2gUAikUjkPX+bxDzLOSNMycmL3yYyXpIMwx+PF4SpKU/I",
	"BflbQaTS/5YLnhOhKIERGU+I/j9hRTZ58esk5oyRWJFkEk0SKqu/foomap2TyYuJVIKyxSSafNnjOKd7",
	"MU/IgrA98kUJvKfwAiaeUZboYS8mgvytoIIkEWeEz1+WU6La/F+/fo3KoRoSgKxalc/+jcRq8jUym7pU",
	"WBWyvZ+YM8lT8tlOTDnT/5oQGQuam79OTgohCFPIjkXVWCTNtFGJjxqM0aQHH1+jCRGCi8B61fwwAvk/",
	"B6ZxZ1Kf5QqLBVFI/4jmXCC1JAhrVHjQbnZ6+qu9FRYMZxp5v/qY1URz4s3W+Om0Nnnw6KLQWQTPM89T",
	"GmP9+zsq1QWROWeStM8WVwPh71SRDP7wT4LMJy8m/89BdREO7C048Gb/sCJiRcmdXtRCgYXA60kT/tpC",
	"AyCXk7bArR3fb+1j1mgP/rDKTnjBlPcbZYosiDA/3mvvN9PBXQM80aROnA4Ws/AALm6mbSzQZJPNN0Ci",
	"mvRgaGjlV4TFywyL24uCBTiBIFiR5BjwOOciw2ryYpJgRfYUhZ22gEqovL2kfydvZ2HcJ4WAfV6SuD4p",
	"L2apNyMrspn5ooMjvAY2kBEp8YIgOkdqSSWiipj50RzTFK5dC0SDznJlytSPz6pxHqzlZOGtZEQtedKG",
	"rMQpMiNQIUmCdsj+Yj9Cq+wzw4quyG4ItBxT8b6LpnNB8tM6+hrsjWYEyVzzZc7003CL4AQ1OjBLkMAs",
	"4Rma0zRFOxWmjhBn6VrDM+I0JJGScnY2FoeSFyImp1hhqbgIb0wBWx4YsxS8WCzzQk1nuRxFOqGLUIHv",
	"IbsNZRsmnxpqVF4n6RagkXeJQhfwBOd4RlOq1p3PsRth/958rNOUxMrckD5G9iG34Fcr6vXnXJAYS0Xu",
	"OwFlMr8/AI0zqnbjT1yDso3E5hw+voIoTws90xuCVSFCOE2EfM3wTLMPuGNzXKRq8mKOU0mixp37ZUnU",
	"kgh0enGJdk6pJthZoSWzC2KICl3GS5IUKRG7iEpEzMRW/KASxQaainxnnKcEM2CWAiSFGhST95w135gX",
	"E708LhTPzJWuSTjVCk7GeVOk6Rodm/HAJM+xUBQ3/3WKWYHTSWTWDIlr+nLgBTm9B8YuzaeAuc0Q87X7",
	"UK8VTenfS6bdEmznNCEsDoiG+qajmK8IwFSNRDkRMWFK/+vO4d7R4eFuhGKcxkWqkYSwRKuT8+u9O0IX",
	"S/0Pbo4gO83wF5rpMzg6PIwmGWXmb4cBRhvnxWe8WrQhPbYwnpxfo6LabgDQbYCQ4S9tEKZmjm8EQv7T",
	"8zYIPz1XS7ceTb8FNjKS9R9IRjIu1t8Ait4z+WZQjDqWbwBNk/3be1PRTkXI1SFWW6hQGvkMIvhwuNfp",
	"UmGhPHtAHQfwK7JPGeVsH50IkmiE4FQiLAjiMBSnWmzNBVlRXsh0jUDSSNCKYnR+fYUO4uqzfS2vNMSC",
	"mIjA6uevp3uExTwhCTo5RnoQnWvlgqBZwZKUhOVOKe+4CAizqxPCFBGoHOGdlfdv7YfhluZXqQxg55bm",
	"6OrdZQ2yFRHmjzV13nsJC5F2w3Z98c4HqxA0BFEhiXAqU3ieckQU0Kl6qSEouI1SXO6WxJlM4BWEb4IP",
	"rVvEPeKC4GRd2VOMRcJRHfwlx0LW/hkedbPEOGtGY4/mvxd24eCPJz40HSM8EIMjzku4+yaAzQQHvDY7",
	"bHIGi8LgzQYZ/a3gRd5p5mvYIuqH+sHd6IWeo2GdyvCXd4Qt1HLy4vnh4b2NgDyjimS5WkcZ/vLy+eEh",
	"0OWcplZ4r0P0Bv4dkS+5MDoP2rnTit+MoBVOqVbik906cEeHT54ZXlv+y8MtlhllL48AYpgeYA5fw7cG",
	"dVTmKV4jexFr4D0qcIdt+6mFwaK4g3Asi+7iAkOcy4jo3gMxIylnC6T4tplYNIGDb3/qJPK48UzZ98jp",
	"EYKoQjCSaKj3w2K5jzy9cQ9gt3oIizXVv3HrqLw9C9u/5oIQrUvGVK3fvgrbaJZYJHdYkOM4JqnWP0ky",
	"5SvfxOA9Mksu1VkAP2eAlTklAvE5oEKP1KxbEKOrJG4DmodjpbDW+SbRhBVpqtWayQslCtJhp047rD1c",
	"8ZinV/BDyCLCFU6H9q+6vl4RlpjXqd98CL+2F2thv5wxckfWjfzG5hwWeinjlChM02HrSOPkmN6VpDHi",
	"83nKcYL88eY0a8c3w5IkiDNkdoNkkedcKGP+yWTdzZOv9+y0mvXov0+iiUgyjYwVT4MKc918HAH8gMLZ",
	"SHOoxvvowQzjU7KicQg374+PUQI/IloSuCxve4mTHySa4fiWsgV6d/1e+qgY3F2nfd7aDY71wNCVOyWC",
	"rjTvETxDHqRnp1pgntMv++gSZ/CUFVrLwEwiqf8hX64ljXGK7AoIYNlHxzNJmILdvX9zCebQlOtx5T7l",
	"/qTbwDHtvKd2wE15nxri7snlWUlM8JGzBL9/fXV8fh6h8+uL1xE6fXsStAi7C9y2VhiC1b+jnZvpm8tI",
	"byxCNzc8jdCHq59fX+wGBdnAA2cvuUeLJZ31XspzTEX7Smrm2CMhvb78/6hhoHp1pDjKKQOSm5WGc8X3",
	"0dkcaYlHkSRC2HwQ8yzjTH8y42rpHZ1mu5IYqbC0g8U4TdfBQw2/oNeSiL2EzKl+4wC20haV642GqKNt",
	"3W4cv7EBVgym62kO2MCDvsuhmcIHPGzfDp4zSYki7/CMpG9TPtPo7PEszudGKG8zGmBHmtneTCVSS6zQ",
	"Eidw4qmeGwmS8ZXvq/EeMBgRwEb5Mcx3h2V7lg6UlIC6yUNbfy0VzbAiF5gtSIenhdgxhmdmdCGw1mrQ",
	"0dUrvVl9Ui2tfUakOsEydKWtF6HBJT5OnjzPnh3Kj5MgeyBf8g6sd8/3Y/bsp6757rjYHMCfsqMn4QlD",
	"evMba8vXAnPIoUF/ev6O3xHh/Dx1KOAnNOMFSzSSf3r+J99YqwlHrMBkPeJ11Etd53nXUvDTlpZytHJO",
	"xNHVqyFXSZ36voIWNNrtFU30c7jR8IRu9gHdZHSvT1PiLE9Jj69eqiQhq/v6/HwXn7fSpx6yJKJkirLT",
	"FuBpSkNneRODXuaZAPuvBRH6Ve2OzdG7UCS5KJjsY7XlwMolLoMMdryVSiMTTFWk11IVfv6rVx+84U7K",
	"rJ78Ha0p7smcxFoQTRAX8JDvuWf9fv7yV2tF5JVWXgJMXP8zmukRWqQoclAQkgK4m/4YW4a3kwsC0mPt",
	"N/0nwEbNft3tCS/BuYaFQjwbfraAkARJjuZYBCAat+AY1ztsIGBEJmLPO+47qpaUIewdlyiY51DMiTGt",
	"mF1ia40RBWPO/mipsbQ/ammTabVwbGBV6H7o/5Lzcu3uIR5QnYMuSmg7h5x42+gc9Nrur3uWcuNjYx80",
	"oYYvvKHh6oqjPMWMBWWpHtY4IvrBEErUYEA+bP1MtekyaXlmY4gojNdBzxbSlJ+mJAUmJNGOdTGjowhJ",
	"PSlw1t3gNXggr26GNDWEIipvkaR/1/IAevsK+JrH00owD3f7I4x6eXk1oX/Q4JSholrkeXgNwNjoeLe6",
	"bmce+zPz4dFA8JtZaJAMgu9aCWQHH8oFXwgiZcWLOUvX5l2ybGbXt0z0bTH40gaMFx288ZKIFY3JXkpW",
	"JDUMch990NCoO27+LhH5QqVC//Xv/xuBmwbt0CQlu/pRs9CiHe9UWbm/3X30i96Tz2rnlFG5JFJ/TSVy",
	"fDOCB1QaaKxxFh4yWHHf487OU+T48aYM12eSdqrwj27+kOclrGKCzX8g8LCtekmFs9wcvsaB8bloHdB+",
	"V5PJe6MV7+3TaVujx/th8tvFgRmOTi/fabolX0A6nbyYWIf5x+Lw8Cl5if7y9hXYqmwwDHqJfsgFT37o",
	"jmts6DCM/q1wGKrMfGjn+vrstCa4FAVNxttKgr6atrciT+51jCnWcqL5eORZdka99rpvYBv9EdMA1Xj+",
	"aQg6wE1yHDIkuDh6/SuySkyYiS8qLSkkArDytdBDw6K+6pODqwnsjgcliGoczGu36MPaifIBdI9GMmUr",
	"whQX66EvzsqB/1BHcTOVKMMqXuoXo7wjP0hkaTp6YHT7DRWqwOkU6xXIYHi7ORyzxKbHrgW/90TdcXEb",
	"8q3rRywgA+GMOJ8bMx+XPgsmaUIMUvTc6MNlkCnmAa/QOcJJAuIElpIuGEn0u2kCyLUAOMdxkJ9lOBB1",
	"PT0+8aZDkhCGZutBwFiFi8ae7T7BAg12zZwLrciPmNT4RpyDvGtmMwqlMAztyGLGiEIZliCKnJydXiDG",
	"FciZTd326ZMwX2id989UKr4QODNg5FpcADulcYQ2jh8rXKPZLkdmxU4zym5wWpAuqxHJQ780k2zcJPaL",
	"yEASot+feVBvyYsTLkiv9H5yfo1iGNTpD/a1lby45PEtUYNzSjtszKw9ooEnFJTuDjDhhOgfhJPpq/Zk",
	"Gj0u2I8yNH0VMlEMw9ntDh/rry690N0+5TM2FzhwlkbEkufGAmhUwQ2pMs6LDysiTniWUZWR0Buhj06P",
	"icsx6EJftX10UosqBu6KjtOUw8WBKGOJDpB5Is6dm/PEUtYIQ2zlLttcGwxtVlPJOb8zKoB1AiUJNULz",
	"eQ23nZirTkXPNh4wuI4dMOkTtOHgYeazCZsBkh4604vjqSP++xyt/dSdrf0rXmFqrsuo07XvyXgUusc4",
	"sGsT7WHvQxiHHSJNdXO6EKxH/ezOOii9bO34mqEs1dJt4vUQWLspYQZiM1O6rBkdloPyO+SsaQ/T0Btw",
	"1BT04G+lfh5NVkkCsgdO0w/zyYtfB+TEJLn1bvTXDTT8M19ED3PcPs4xSqjXVNdS5ydTnIMnxKrOgDYj",
	"5xEqUKk6OEdtC/JV9QRsBIX97nPo0T07deKsjdcLhunZCVZEyKBl4sb80JgK4ZzuozdcIGtOQB8nf9k/",
	"3H+6f/hxMqgxe1BH1cn0nuipFduCp+qnV/Whr5mN9bVcvZHLM2IS/wvQDu1D3398etD4476x51ZpWr2j",
	"p7KNadCeDHAh/E5NJAFnZ1IWoUgLKYmU7iVqUU/c7UztSCQuYyz6KcQMi/z13WqhbXQreyt5R1W83Cyj",
	"2wVCOZYpFWYJFjZN36Xd6b+56aNJwWz8XkexgVWKWUdw6SqTnV7pcIhkZ451KPGxnSzgp8+FgnNtMK4f",
	"o7vEK4JkMZ/TmILlQtAVTUnN5uCFt2ZUSsoW59Wotm3buF9jtLrMIbq1mtIE2mBBkJ1ng0DABsLcXkPI",
	"OsdU9OGpP97zDcGSzlJShnuaDGxZqTbG17VnHFwuruuRYjv7Ix+2khj9MKfeYKps/TQeKxzid+GjuqCL",
	"pZL075Qt7GvSbxf2hZdRULcXaDxXTfIxhp+gGHEF4fj6Z3R2WsUwg/EcLxaCLECxmAueDT781TID7357",
	"A4PYeTBOvh8ORqKgP+HYjAmC7zjslF+QuZPk7KQnPMsLLcvbFHIItUMfJwnPMGV78dGTpx8nu8HQVrdk",
	"2G1z6jls3JpOPm6YGp1Q6dbOBU8KyGfcs190gtCTZn15Pd0xloz//A8vmu5Pu+gAlb/t7jdyqpNacvbO",
	"4X/9+/86OjxEf9rdR2cayFwQVcsxjXGhbFIluJdSfrf/kY2MCuxKvK7DbkY1AAePbwk27sjU3vnT7nhQ",
	"gsm+v7glZJFlWKzB2UDE3s0UZfiLiYqXaEcSgmwWLGK8EanUv2wwu7eGgRXkz7ZOrgc0DYYFTeOJcYUw",
	"0jq9o8G9O5oQGLZzt6TxEt3xIk2QvalI0Yzs4dQY7E08n9wdfa4JlbfhLeWCr6hWqEjyr6/01vTQcmO1",
	"XztOGGqt3OuIO7PKG0tPATA7OgTbtAu2QAr2RtBtTIBmvS3QYWeW+fDqHqndd3UwF332MPw5zouQzFxk",
	"ev2VsfMXTEmEY8GlRDhNwYNn0xtaBS2aZrHaYpqkPt/OOtfzxhry29HUObTyvfZtcPo5GwfMxfEU7UxH",
	"wBIy/n2Ow57Veg7BHVXLGkHDAwELhAqHdClu3vPceDg9UKIHVRQAplN7EjsJqx/zfSQyJKmYHOlO6X2G",
	"Vbz8LOnf64VmfnwW9R5CTgT6fwsi1udEzJHgBUv2lKB5OAivRxIyEpDJ5OJzhLukIMWRjHlOTNHDFRFr",
	"K5x4YlEwSngbEYCw4Gdr8ekvcHM2h0ctKuEEdKV0RUw6m5X8IMMJJihD+HYjVEjj09af4NQEj1nV314g",
	"k7ZWmi/N+9fW9l1+QolyC/KfnxweRh2y6JLqpaiZ33yuZWvKkCQxZ4lEO08PD18meB2ho78cHr68I+Q2",
	"QnrKlxlnahmOQEw5v53h+PbzkhdCNqGJWhkeZjS6oyzhd3p1+K4KdPzzk0P0Ej09RAley/CS+hZ/HgjJ",
	"0iieWVlYFrPS0t6vKvjENHDxpkQJGnfkudjneWQSRYqVvbtj3k3zYo/JzTCv66iRP40caQSzz/FI61lt",
	"eFSixcBm1jU7KpEwgPULUGI2U8bGKGHAe/z6VGWBF7QDZRnQS3jrnA7dxYq0VvoZb1BS0eV4fW5itqUP",
	"c0Eg7RHZ4jlOSC7TLeyV2nE3Eh2UF70jQDkUOHBdeTGMxhgMvKnzn8BjX9nbu4sjeMkiNZQH3SbZvYwx",
	"N1NLMQETjMHXZ8KS8cdlv5EKi9GHHIpedPiJ6nJKbfoahHWcd9GNi97yKHHUheq3hhk6COXrUak0sVhL",
	"jRHYKZH76FoS9Pb1FToQ1VIHv9HkK5z3vACxEWXAQyE3e9ODNXBfGhWh0809HIRnn1+3xUGx0hsIC4xC",
	"rwOzHVtQjXRIzIjCxtRF1ZIXysdTD1ohNFwJSlZGxAAU2ykpi9Mi0Wt4CP+Df/5fxT//WzK78WyufAfa",
	"Bd7NlbhvmEKHRBgKgsr4ZrWeo8kdFoyyRShakLM9c6/KCPubKVjH/1YQQUmCZoXJxGfcl/ztbkGn3r+/",
	"k8/Vb+JwPA6FHsCh47iGmP8/6nBtrw6XB+zvsBBXGDpbiauDOnoCiqCWf6M0dVdey31SB5qcq/wlKpfu",
	"pmqoo3Ez7U4qx0ngsYCSGRzhxC+YAbXBRt7Le5xFQlckKjdqdp3ZqllB6MzPHoDW6fbtQAyRi4vUGVdP",
	"v/0qhY7yZnpapirUJ72lLOSkXOdg1FqZRAuXvGBrZ8SJ4FmE5inP83WECjmLkCSC4jQqM15HVtW4mZ5a",
	"/0bDuBcyWb8qpC0cZOCQsaQRogmJkMQKR4itsnCBelciqCMT1v2MKDOJ9eMy1ec0DSWhY7W08XroZnr6",
	"r0gPc1awxA9saEJ5S9ad8e63ZO1i3tcmq4ZKY0C3We6wXD0vZkQORFfLEUALlOO2uM6JkFQqwlSEKEtI",
	"TpiG5nPXvzPOqp+CZyKSrDtsyCS1SITRBb5DhnjRFOc55KAmVJBYoXfX7xGOYyJ9oduzJcolFn2xSRUO",
	"qURmMJoRdUcIQ1mRKpqnYNEcWcv7ZmoeTfOYy/HdTFqoV5TFCiVE2cpQ1XgTDrpRMbO4FhAdXKkWa7rZ",
	"5JzFRLATrMiCi2BwU7WKGYviavA9loL3aMwyqRm4yRJJPQy861zKURsjLOzJcbHbbunmXkNojoZb1dxM",
	"OyIx7QGsQ0niKyI0I3RDnMJH9Uz76JrdMn7nH6EJrcN5bpLRfvigb9YPfhr3iaCgnU6iyS9GiIY4b8Oa",
	"jIR7nKyoNAKJK0MB84wMKLcbtdhZews2fqnWb/xQB6fxowdd4xcHbOOfLexDidqmNiRJfHG/hm/jMKx0",
	"N03ainxRpisKiXmWEZY0i+QEAmQbh7zkQlmJx/wyc3masOyg6usiaks6qm80TIuGlntCr8AHPcqFSnC8",
	"tPDvQPVELhITCWTuvCmeWEtQ//V59DR68sm7qYHS7D0JNekQ17Erm3IgKgVRopCkBoMXjGRKkyxsmRlH",
	"sDX4ehWXHCtFhIbg48fLSbQh30krvgJID5/Y+7OTgBDKEvIllCOSkC+OeN+fnfRKJQF7U756dmySUUN5",
	"r6tnZaqqq32q12iEft1M7zQzuuI8leGc2tWPfYv8uI1FBnNtXfKDlaw1kjdJs70gcyKgkpsVMV1+cQkw",
	"GMxco71QOeaw7OIMnq8EwbcJvwvEBS795NjeNLdyoG+u7ggfecOFSR0wOZbjxv1C1fIXz4bU/c17rvqn",
	"D6VbTYKwDQLStWr4fnXWSftC1brsyWOfjvtY8FwFoCtKhOdPaHMwt5DjsrO1qwvJGapgQlA7JkKECRov",
	"SWK4sUkLTMqKQjkRZuA+uiy0DkASAmJ2ucyr9Uk5534ohcnPT+5PU2lTrQ2Zq1bQu//mGLRBRPr7PQ+B",
	"CmoVg3XbpsXbCovQIZItKLPdRa7oqwgdHe49MX96crj33Pzp+eE/X9FXu7XwiQpxZufWT3BPzL199YCP",
	"HbK2jPDgRq/WOZEPWUhPMLBIkGY3SxluZ4I+8AKincOX11WKUISOXr7Gch2hJy+nJKFFFqGnL3/GIonQ",
	"s5e/LKkib1Ne69zXucW8GDq80P5GXoaT82u4AGhWQAmAqhTr4d6zjxP9h+d7fzF/+Gnv6Efzp6M/7z19",
	"Yv749Mk/18q1dm1jCuFnj7gTs8DwZkJ7eLr3o/39x+d7R0/sfo+e/LT35Lkd/uT5j+M2+p7G5W3f5jZn",
	"a5AkQDr0NmZBtUDa/Zj/PesCuCRj/7Ue5RJv5BOGyrR7278Hv2L+G31BsNykuewwdFw+lE+0kMmlVlTv",
	"y/Ls1yFOl2+tHoLA2b0fkCFJcZSYuLGMqIddgvHvlMpbObIQ+IogrFBKsFSIM+LMhzZwdhMZsyZglpKP",
	"w2T5JvuPe/3AOig5dPeCgmg7djRgMbpn1y5w4kObrLWzMTg/f6OZ1j6aFlojSteIfInTQtKVNYDYnlzt",
	"pJ3NHTBwEn7XsFBTsEfo1QPrdvYWg9KJJva2r8MYWKlvaZ6TRCNLKkhFmREkiQJtUBQE4ZSzBZSYMmcG",
	"yRVAszHPZpSZmVzZxWeHh7Zyo+1Z8ALRufuSSoRN+wkIgPdapd/SXAKoNfB2Zji+vcMikSCyYEVN/uXu",
	"v9QnhVhwTTGNac1kxMxcSEMvGnAPH3o3Fo+IEZJUKGBq/1FasG1+4nrFr42mR49DU0Oti0qi/qTveb0Y",
	"RtvltlYh8311WljMcJpu4iDLkkAWTJY8R9LkX2gCKMtG2/mDIZJdFSWulqQqNOfCwU9SSCt3Hw1WkCjH",
	"aXCDHNKMcG9vo/IfVabGTiAggZreH1Shy5+PjdqnOJoVNE1qTfzbFSjp29HTWjxen22yQCdGodu/w51N",
	"VFg92T/cP9zdAJMVUup7CWK3bh7sy8ltlKTyvFbBKqm1cljtTjSeD6evJXxXpGXi11AOVw5r34iqLGe7",
	"YqCsqlgaax6kRap4uaGjLBS8V0eyzY7oqeViu1hTzk6s62kowan6wnngJPgoROLVzTeh8KUzOfG/EkQW",
	"qQqbh8tRVemiXvkyO2t+oWcBH83gPvQoiebQP6MMQRxhw+5yEdT681g3QTXvdPJINv/7Rqc0I5pcMbGA",
	"VdtowZtegawmxTdulhZhqLWQZ1pYqEYD0qZXN/voDWQfcbUk4o5K0lE1xMq+r7UwmWzS4dvdPSqNJJq4",
	"hl7lnMEVw0FpjYvX2UeJZHkarL7VRglGbvQ4VHgZh59H9BIvW8WArOWFpaIDFAxXRf/5H0jTyqg0zRow",
	"XXnizcxzrCAvd+dPu//iRFIIDmW8lU55PyiC6boBKCDH+1GgCKd5nwYStB9h8e7u3O0k7Ec9i87U6TAg",
	"2z0O+xxehqvgOZXBtBZxUVFaDSfJB1b9cT6PkCwkxEElo1vZmWhyH4CqokdNkvHkkpIz1562YRGrsydl",
	"l6D1PlB2I+ZMYcqcUt/1PtbKa7DqRSbB/uOqWqZSC11EVlkujiWBJX8w5V/RTun7tIms5d+4yJeYmT8h",
	"ykzgGJ2lHRGDXBB5ToSpajuqUC54vpxf15S5HReCF+fF8XxOWTBA0WUilR0i9XpnpzKAA1CuKbN1ofVz",
	"qQWipEgbZa9GgBSoEDuyeLhDANTbwGWxUBcQeY8IxT453idNLy5rY+pMutqNOvTDE9uIh6165nZub1w5",
	"cxedGwpJC9skHVglQHrY9sDRj1EAGJCernhKBGYxeT1U+83GSryB7OfyM5CrzKcRMvVSMkzhvLRsAwnn",
	"cokTftck7zlcXKkwU2iOacpXvvLiSTxzKjK9dCitwfxi4oh9R2xjrZ0Z5dC6hMxpkEHMeZqEKLIVoFFV",
	"7DSfbE6cUDr9LBhlD3tp1cKuqq3X4qXFkqR/+fzjMyhqv9u50vugIPumSNNaASazBDdVAtkCybVUJNs0",
	"XmbhFdiX3bXfQSxduFaOgSL6A+uOa4LhF/vvqNI84sCrnnGu1XaIUVddxoKt6MKH8DOXqn0Gg7vfpOdK",
	"gJiawI+0HGyipV+A8m/U9LwzSOtcUKib43VCeCgiQNvv5q/WGmCar5Zx9/flq52+wv/mtoNQ6f3jDHRH",
	"Pi8Lh/fLCprsMrLAIfNzV2pDj6WhUvZbC8VYC51W2ycJ2lFWBWccuVBNSxi7v2vbQ6hs3vBrw4hUJPn5",
	"ZvB5NwOdCOL0Lf9110d6p2/Ncp0TAVHUJvGqqPHwLpj8DdpE1n4pyMVClt1QUAzuqG3JRe/PToIFU0tn",
	"bE97HmgALH0dpylxdCiT0M6/W58sW7lfy9BhGfHcdZWXOSCFM1lknaLPZklQ3ZarnitWs2Ihge04zBBG",
	"giyKFIsxVKE0W7fl4SvLcK8wCi8BxMiWkdqutZ0NV+5rVAMLdq10pkXTNHXdpvUgEzTgLbwDM7znyg6G",
	"fnj2n+xG7D98SN1PH26Dx16MrzN+k3n1Po36D08tJJmGBIEVERJc8UVLKChbD1XFNjdqa+ZdlrZRwFM0",
	"Wyq495g4tcjyhWGTR38VkH/gxlrfp6HWPRpp1VcwqcWdKcWbiEM7guQpjl3zSo0Y88tuT+7Fo2dc3FeC",
	"YlzNUsxuQ6JUWKoIclzupIdSoGgJESVqarFmjrneK7QmmFjgCfnWlRhSoWx7VGPVkkoUsSqESUHO9kqw",
	"90xKJF0RlNKZwNC1qeV2bJeA8fLd7pMkVc+7JW6hcKsp6Dw+nKjtBtayqAwsnwbQ6HSlQSdv07cawIxD",
	"2WhGETjOELfo3UBX/5nxPd2H27l7BxEyMyf2EQzlJXehN4jP1kZlvxzo0Wuzm07VjTzcgbzsPO6akY/M",
	"jmxhvtF/vGNA1Vi8Y4DfVrxrSAVyxwiTQtnRmKc6xvCdCEg1oR7d39fj2VmYu+VfdIXCN6mzvVGFRc/h",
	"ulk97XvXqT7dfoXpkCtwU8zpyTerTVl5SDerAD1mdFf1pOEizpUXytQ39wsa1+1EAbl1TNXm81C55nE4",
	"HlmK+TxQg7mrynJHOanm02pqN7nxATx2ARdGylApZe8aDtVV9uguVGT5U0emUzMjqsXkQBSHUa9Ghatd",
	"varIQ9GxJbZX2cmYMteuoLWdeEwsvAW9WuJTT87Xo2ABfrAtkbaHio5kAVjMJRnbRQfQ5BaMarv81Jsk",
	"Ekiw7+g7W7abqn72A4jyhcAJuahVHAhJ8fZ3kqAPl8h+5cK2kNfVChxTENptTK12KNjnMPKHDdc1tlgJ",
	"dcxyOPlqmqoBThRV0LD+WNoIxDKRB5nQ1+Pzs4kXHztZHQFSc8JwTicvJk/3D/efgrqrloDXAxNk++K3",
	"ycIECnDXOOssmbyYvCUKJrZCL8iXYIeAj58cHlohRdlJvLIeB/8mDZ6N9D0km/vLwJ5Dkb2yDId8bpZu",
	"yrhaycUpkkSsiLDyNWQvuFund2QCi73Jcusaq+/90u59yhMyMedGpHrFk/V2N63nd8aERlS81m6/fj+k",
	"a8hQvMRsQRKNp2dhpENJPSTcFvS4nwICI2fzlJpbfu/TOwFg7AFC8Sf9+0GzJlEnLfvjHhOv1Zc1410A",
	"x84L4G/BZA6VpjLoZ/gApMESoXpMpR8XcYZc18QDVwzUq2Xr4bSd6NfC8juQEdptm0B0wQJnxNQo+rWj",
	"bOPp5bta6UbbDKkqUopeoh+8/gM/fJzs7qMPGVW23G4hWK2qLVTU1Av8rSBgqjCi2GS2fl0uo7lwebbt",
	"upBNPv7pEalnoCtagIhcMkFNrXDtuKS5ks9C1UpRqaIj0a55DGHkD+a2rs+QSf8Og9iMsffAsnXCOyjz",
	"4LeyjdjXzai0VQ16LJUGikNfX5+dOhrTT2tFYn6Tszpf9+mtJSX8cTO+780wFAH5ed/4EmAkXT/QAOnL",
	"g9+qw/560PCidT17gbZ5AzReb5QXboWHuEALwoiJM3ChtWenTbLcw0/nf549iY+SZ+QvPx0ePTHJ9oHL",
	"UitD3X1bKmfG/9hxIH38mPzz/3QL/nq49xPem3/67ejHr7v/NPneNLopfUKZeXB5hDlii/8MymYeg7Dq",
	"4YOeBHDrl2UX3R3RSmkFz4Nui9tzADmztUdq9m6YCuvO+q5hD0jziucn5cDW+T8LCaxlrXypeJ6Th3EB",
	"DYBfDP5r1H1fHZyPr3Y1lwqRqBuyLfUrDkzYoYIpLFT91LavhPkoEGojTezJdzgH63wBa8HDdbJyStf3",
	"ijKUC76AEMaHkTuGFhcufNinfLi09YoN1bVtPsQZXxHT0M72BHGpFH5X7pJbat45w5JowaZOS6ewgl8o",
	"YhQT8BYxMD6MCxgoAo3FPX7QxICpdtD6pGpJsnN98Q5xlq5399F7sjKV77kkUKxLmAA6gVw+/T66WkKc",
	"W5JzyhRKOJHAxQVxxfFruMULTJlUZQu1SUCY7kXrFrlVuUzPNakQVLGXzrfO26dB8IO5W/ucPC5XBA74",
	"xiJd9mE9QoTFYp0raxyA2mya0BN0S9YR5BXByrLess7dB4RNdAI2AQg+dETto2Noxqa5BVPo/PoK8RUR",
	"d4IqYj7LBVnZ3r5t0m1TxHnRoojt8+1Q28Bvaz7bjBxl1XuiOi6gtyeHR98NJturpQFRvzTpfc4FKpgg",
	"OF5ClrOLqXugoCRIiMu3Ho6DWi99X/uv7XZJ4ltZFtjIBV3RlCycvpWmqCReiXZK4SRy0Q76j3MuSIy1",
	"1Llri7sErgG6pGyREpME5JaL9eoRRF9DZMtigH+e+Ft6TNp166x76KQc4yJCcyIqbH1DxgpnWOK0hADV",
	"CADIQ798QnUSw2v4WSJJUmMOhQcU2mRJzSNPLm+g5YFEOY5v8cK0AMXo/z87R1jES7oiUBnUzDJPyReq",
	"6d70SDWTarg0ZfH5PKWMIMxwupYUGPPrLzFJQXsqpNIiC+ch/mmgPPNanfRq6yc8y/CeJHqQ3lNqbcp2",
	"WxBQB9qb6+b5Avj7ipK73X10vMI0xeUuZPVjBIlAMirNRVHVAkJGaJXJyEWtR76SFrmQ7T13b6Ka2Tmy",
	"hUIiL6DID+qblACY9U3EZshOBRBP+kxpm6n6f6d5/QqV3tQZZRhWbi7QujUeqfjZchVlaeKwDyJJLNI9",
	"pjv6enfEn1VopJZhwxIvUGHq34+pqdze1Zk/l6kEUV3oh4J8L3iGuYa5RpCRUuoh+p2rqpPmKTYOEEi0",
	"BwZSsfo+vURr80Y0ci6UGWHxMsPidh8dG11qz7OkFMw0G4BQUbGqOgt3Kyx6iTcVMI+ofFardL8Fr9z2",
	"kIvkg7Y50NrEGJaNBxx23vcylHjy8wgf9DYAPNW8g5qUTZ4owTfxmCBW50Ts5ZiKUgd2sZbBV7uFt0d8",
	"r8eckQvTrEi41D1qGDvnaRoaVJlhWlGn+rXDcs3iCs+a6OGdY6BeZlpqK58HpLEo91FN1DTxEloPBfqH",
	"11FPYKr3ITr39YyydJt+fxkiWKSUlIwzdF2wUI37sn2lo3YM381atNmFHWst8mS2yOkqUNpbX7rImBCo",
	"QCnNqELkS0xI4mYN2JaOmak6ULvvzsq0jXtvLEzeta9z75ZyEKZt2zFV2mR+LbRxnKCMqCVPDM+eEwyl",
	"NkxRCuedMSVg9xQWC6KahI+Mag51IVkCSXAgMpZqFl4Q0+gDKZ7zlC/WKCGCrlzGJKTHcHGb0rnaszoJ",
	"3AXXgR6955WO4dsNBEGOEAOKOZfeHTnHVLT0je3fmdoy60cMdRmVBFCHJhD/360GUVsmRR9x5206LSlh",
	"O95DS6Dm7rX1HZ/gG0Vw+41NpYJts9hWWs3T5FlWMoUCl5IItLTGI3daXbq096T4KnV1N6CZXIYZXpAM",
	"mq7dTKuoX8gehODCOIW/7e6jG79EK2fpGqLcm/SuES3xKkjwhUfvv3Ob1IDhCA4HQ/toewwe+jUaFgIz",
	"tTX7zbPDp9vWRmQxn9PY1DdtUVCEMiolZYsX6NfyDu0f27z6S8j9recI7ZcK8v4JWLE+BXNpzKzn5UI1",
	"qH6ddKw1aWb9tVarpd8NtzAa1GiOC7XUx2KpXRaxeWGhZTDcwxTHtzJ0/A9iMHDH1kG3iqa4nAhAIWdt",
	"jlNZA7ofWCd1V2PHvXC2fLZ9K+0zqgGKK6sUrTqf1Z/P98fHru1nlf0r7/lo1iT902rLjy1hVkt5b+Y3",
	"eSPLlW21tRGPpItj9EjiwTGLuLRM+bM2aBDkrYPfGM7I1z6N3aiJ5iGrZNJGyA08sjNTdGIfXRkSdW+a",
	"xjFlBanCJqkrrWWEPk1GUtE0tW6WIZ1eiyJDtj09xtTAwNLBWVkPQLQv3bzBoBqbRjI++OzTAxWXZno6",
	"Fe+7GqmX6YYui7DMEvx0LyPVuZGR7ByjjBDC1S1w6k0Vz3JQqitzyqhcPtSGbewUGEnjJjBSZIOaRcG6",
	"PRmOlVKW0BVNCpz62pVyEtc+ch3Z07XNsTcVD3JHSwM87qJgY2N1wbDlT91hqC3JYHu22nvytlIvvijY",
	"JoytRjJbYG7N+QKEcPCbjWrtCmoy0QS1gxuMXi0Y6gpWHYi7G6ynEjjAUGxlwfxQiv4AFgNtZ5hmwbak",
	"Zdm4DFw/ltapaIY1fD9jo7IlYFijUtHYxXbWzQQ/SH85k5W9j1ydsDJAw8VGX58hxbWGBHWRKiO2olnZ",
	"io2MsVTK8Y+O4mhBVGMjw3f8Ia/N9m2mZs+Bu321FLxYLPPC32EnUU6NJoHcPlGJwwcHjagwIJr6qqL7",
	"wXBBzUvemiHjOLat0W+FHLQTY0n2KJOESQqxIbKYmdMxGSi7nSHig/w8atNVWY0G7RztQTtWUxcqTE+L",
	"+vxlFbKjqOqAexTKPuxObLTbN2acBelZ2pYpDiz/5DCaZPiLXd9WW+mG5jFJHI5+bI6RJaUhpmtEBi/R",
	"YAuSfJp6q4eDPY1WDRt6rEjPaoWNrJBH2z2u0BHBDy4YZ2xcpyuNSusHJ9dM4S+7DxNWARKEESN35uR8",
	"bjRSMHFn2cuWzM4fKpJAMbAxgf4BKcJAsMXoTouv7gDv74+YFoe8hOh+StKkjDAUNpil7KGol36BZfxx",
	"orWlMsHjhZ4pqn7c3Uc3lh5hOjDR4oxEyK8RX0aVGKOv5raRraYZ2QKVEYrz4lriBTFj7B8Fzuyf4rw4",
	"Xi3gs+MVRFZ5hj0HHZaxRRsAqlVL8iVPeVKWjwpGlnChatx/fAsbqdZg8NRnMOl/BOegdS5sZ7Nv+Q7C",
	"du71DH7ft67vnXMXGTz2hopt7uyz7nu/vRwvuPZasDo7NYtTJR0AuRal2rzAlJL7nfDJ7T+43va+U4b7",
	"wINbAIBbfHAfndAMSv0nuQxTHUp/OvOD7R4N42cOnO7QhJupRAISO6y5/m8FMaWlg4dwXKWmGNueib/F",
	"inRivATCJDZsJdqA51VEMCJMUUHSdd8r38TEwAU/m9s2mpSZ6odlc8Gb09N/9bI9/mrre/w1Qn/Nkud/",
	"3TVl5WwVwn0/nga+vMMSMUgLcTN2pf3alW+S5Db84Njyz80qK4/K9kcQVHXcW0pRo4EJe1LUGjfrfow0",
	"EHNV7zDnjPyNyjh1r/+m3ulossrOErmJhNMq7qO/Dxeu+XYhUeOpZJsJdBXhbT+yyTt7LSaW9TlK2mwF",
	"fAQJ1EV8lKD+w0ZB2MfaeMalnBdpuu48wVc4QQ1Cv7+H3KXFBVMPTV8X+wQ3TmilOWlPZn55KJrlPn4Q",
	"aaOLbuCOOBM2VIp1NaTLL1ptb215cHhmFBb7H9mZLQ+v/8WmUED8kGl1TFj5bYQwenb4DLnNQjiwDSTe",
	"/9idXKL3sEWhHQBtZei1gohqB9V7bbIiVTTHQh1ooXsPAst7/KNzGmrw4BBqewoPZyHUWTJMej+O/C2J",
	"7RpIwbvPvbd5kwJTz46ehtonpcTGrUr047PpKxPK+kBxHLZQOy/LA1zyTu/1H5nh05INy/7IZ2UsQHmR",
	"dk5sA/OUuEpSrMCpF1pj7uBulxioPzo2k28mBnbVralWVrxZBp5Ko8z8IAOG5zB8MN5UCXk8xxJn5MMc",
	"jqJf7HAnqDc/rAt74z915/j7cVA9Oo5DquaGZazMtsoz1GHQJB0uCNZ2R7UqKz3qm9Zabaw3pF3dRG7H",
	"0dExcVg8uxJ0sSDCrxpTVUp4HPGsvdZ3SmNoHZ0rjtpf/UIZlJHkX6zAIMfWwfGekHsfsz2w2ilnRAka",
	"y1aRi+FCZcNlyQYDOh6nBNmnb3llg5JoR5mjb1Gtyy/C1a6BBG+q1j6gx705+t7zLqt3bcY2/yhI90dB",
	"ut9tQbohUq8VqtuI4Z2UnaN/d1T/R1m871wWb/T9ePQSdT5kjWvilgXXRsf1KUt0d1+MGzvkMVV0swSU",
	"XA/5aczPfppFZzXtVcfYA9vJq3OX07GBa7N17akBFZKAg9W8yKZOkU0arkbWOmlNyJf8aPtPzB/RFH9E",
	"U/yjRVP09BjsUZrLeIoRznLvUj+4IGi1vBW/gSfotx9y1KpDdzznwIzY4/lgVfibqTQs5kP+6JXhb6a1",
	"pfpQbtme28BDUZhAf8FYOSubmRetcFpYSa/0MGn0VV0Mu9H2zox5VHSZNcaQZrlBC/qDlcA0bc6p5YdC",
	"EoRjwaUMIezgN/j/iOBI2NjblM9wmg7af6+gEPCMpEZtyviKWPECtFAZFhxNR74+mfFBXSMflT0FkNRL",
	"BIAcF1SycGgdYlUGp9uJ47fBn2bK2uEMxX8B8CMEoRoVZDyh8/V3PPjHChdz2Ng8YixEEl6tuLIak+9A",
	"Rjv2lEr3MlY8o7Emn93N4gMCaskHrzaOXqPSRHYYt61VJMpwQh4Wrj0FYrDEAVYpLZnIJc3RDk6SA8sy",
	"HPEcAHneTOVuxb9+G9DToRFbL3k222Qn9wpV/JZMpg6xS3YOKEL1nSVVE+qwi7o+fHtGGxfaime8UAij",
	"VTbIW77rsT1CaElPJ+b7Moqb6WahJWMv/810uzGfplhK5U/3Lu6BV0ixR/Iw1bRvpm8Ez2oxaw0C+Z3f",
	"2nY33ocHmQYjRjXvblyPGDMTyjKcZ97FBpBdxPrtS7juTR/mWJuQwqa9IDK7To1sRjYQuZlu0DukAYax",
	"ld4zbv3bklWgI2+QsOpmyYHH4D0PNPcAMvB7nG7THDkTBN8m/K5lmNTrwKcwlzm7QqSTF5MDnNOD1dHk",
	"66ev/ycAAP//swdhvJcdAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
