// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

// Defines values for AgentModeRequestMode.
const (
	AgentModeRequestModeConnected    AgentModeRequestMode = "connected"
	AgentModeRequestModeDisconnected AgentModeRequestMode = "disconnected"
)

// Defines values for AgentStatusConsoleConnection.
const (
	AgentStatusConsoleConnectionConnected    AgentStatusConsoleConnection = "connected"
	AgentStatusConsoleConnectionConnecting   AgentStatusConsoleConnection = "connecting"
	AgentStatusConsoleConnectionDisconnected AgentStatusConsoleConnection = "disconnected"
	AgentStatusConsoleConnectionError        AgentStatusConsoleConnection = "error"
)

// Defines values for AgentStatusMode.
const (
	AgentStatusModeConnected    AgentStatusMode = "connected"
	AgentStatusModeDisconnected AgentStatusMode = "disconnected"
)

// Defines values for CollectorStatusStatus.
const (
	CollectorStatusStatusCollected  CollectorStatusStatus = "collected"
	CollectorStatusStatusCollecting CollectorStatusStatus = "collecting"
	CollectorStatusStatusConnected  CollectorStatusStatus = "connected"
	CollectorStatusStatusConnecting CollectorStatusStatus = "connecting"
	CollectorStatusStatusError      CollectorStatusStatus = "error"
	CollectorStatusStatusParsing    CollectorStatusStatus = "parsing"
	CollectorStatusStatusReady      CollectorStatusStatus = "ready"
)

// Defines values for InspectionStatusState.
const (
	InspectionStatusStateCanceled  InspectionStatusState = "canceled"
	InspectionStatusStateCompleted InspectionStatusState = "completed"
	InspectionStatusStateError     InspectionStatusState = "error"
	InspectionStatusStateNotFound  InspectionStatusState = "not_found"
	InspectionStatusStatePending   InspectionStatusState = "pending"
	InspectionStatusStateRunning   InspectionStatusState = "running"
)

// Defines values for InspectorStatusState.
const (
	InspectorStatusStateCanceled InspectorStatusState = "canceled"
	InspectorStatusStateDone     InspectorStatusState = "done"
	InspectorStatusStateError    InspectorStatusState = "error"
	InspectorStatusStateReady    InspectorStatusState = "ready"
	InspectorStatusStateRunning  InspectorStatusState = "running"
)

// AgentModeRequest defines model for AgentModeRequest.
type AgentModeRequest struct {
	Mode AgentModeRequestMode `json:"mode"`
}

// AgentModeRequestMode defines model for AgentModeRequest.Mode.
type AgentModeRequestMode string

// AgentStatus defines model for AgentStatus.
type AgentStatus struct {
	// ConsoleConnection Current console connection status
	ConsoleConnection AgentStatusConsoleConnection `json:"console_connection"`

	// Mode Target mode for the agent
	Mode AgentStatusMode `json:"mode"`
}

// AgentStatusConsoleConnection Current console connection status
type AgentStatusConsoleConnection string

// AgentStatusMode Target mode for the agent
type AgentStatusMode string

// CollectorStartRequest defines model for CollectorStartRequest.
type CollectorStartRequest struct {
	Password string `json:"password"`

	// Url vCenter URL
	Url      string `json:"url"`
	Username string `json:"username"`
}

// CollectorStatus defines model for CollectorStatus.
type CollectorStatus struct {
	// Error Error message when status is error
	Error  *string               `json:"error,omitempty"`
	Status CollectorStatusStatus `json:"status"`
}

// CollectorStatusStatus defines model for CollectorStatus.Status.
type CollectorStatusStatus string

// GuestNetwork defines model for GuestNetwork.
type GuestNetwork struct {
	// Device Name of the network device inside the guest OS
	Device *string `json:"device,omitempty"`

	// Ip IP address assigned to this interface
	Ip *string `json:"ip,omitempty"`

	// Mac MAC address as seen by the guest OS
	Mac *string `json:"mac,omitempty"`

	// Network Network name as reported by the guest OS
	Network *string `json:"network,omitempty"`

	// PrefixLength Network prefix length (subnet mask in CIDR notation)
	PrefixLength *int32 `json:"prefixLength,omitempty"`
}

// InspectionStatus defines model for InspectionStatus.
type InspectionStatus struct {
	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// Results Inspection results
	Results *map[string]interface{} `json:"results,omitempty"`

	// State Current inspection state
	State InspectionStatusState `json:"state"`
}

// InspectionStatusState Current inspection state
type InspectionStatusState string

// InspectorStatus defines model for InspectorStatus.
type InspectorStatus struct {
	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// State Inspector state
	State InspectorStatusState `json:"state"`
}

// InspectorStatusState Inspector state
type InspectorStatusState string

// VM defines model for VM.
type VM struct {
	// Cluster Cluster name
	Cluster string `json:"cluster"`

	// DiskSize Total disk size in MB
	DiskSize int64 `json:"diskSize"`

	// Id VM ID
	Id         string           `json:"id"`
	Inspection InspectionStatus `json:"inspection"`

	// IssueCount Number of issues found for this VM
	IssueCount int `json:"issueCount"`

	// Memory Memory size in MB
	Memory int64 `json:"memory"`

	// Name VM name
	Name string `json:"name"`

	// VCenterState vCenter state (e.g., poweredOn, poweredOff, suspended)
	VCenterState string `json:"vCenterState"`
}

// VMIdArray Array of VM Moid
type VMIdArray = []string

// VMListResponse defines model for VMListResponse.
type VMListResponse struct {
	// Page Current page number
	Page int `json:"page"`

	// PageCount Total number of pages
	PageCount int `json:"pageCount"`

	// Total Total number of VMs matching the filter
	Total int  `json:"total"`
	Vms   []VM `json:"vms"`
}

// VMNIC defines model for VMNIC.
type VMNIC struct {
	// Index Index of the NIC within the VM
	Index *int `json:"index,omitempty"`

	// Mac MAC address of the virtual NIC
	Mac *string `json:"mac,omitempty"`

	// Network Reference to the network this NIC is connected to
	Network *string `json:"network,omitempty"`
}

// GetVMsParams defines parameters for GetVMs.
type GetVMsParams struct {
	// MinIssues Filter VMs with at least this many issues
	MinIssues *int `form:"minIssues,omitempty" json:"minIssues,omitempty"`

	// Clusters Filter by clusters (OR logic - matches VMs in any of the specified clusters)
	Clusters *[]string `form:"clusters,omitempty" json:"clusters,omitempty"`

	// DiskSizeMin Minimum disk size in MB
	DiskSizeMin *int64 `form:"diskSizeMin,omitempty" json:"diskSizeMin,omitempty"`

	// DiskSizeMax Maximum disk size in MB
	DiskSizeMax *int64 `form:"diskSizeMax,omitempty" json:"diskSizeMax,omitempty"`

	// MemorySizeMin Minimum memory size in MB
	MemorySizeMin *int64 `form:"memorySizeMin,omitempty" json:"memorySizeMin,omitempty"`

	// MemorySizeMax Maximum memory size in MB
	MemorySizeMax *int64 `form:"memorySizeMax,omitempty" json:"memorySizeMax,omitempty"`

	// Status Filter by status (OR logic - matches VMs with any of the specified statuses)
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Sort Sort fields with direction (e.g., "name:asc" or "cluster:desc,name:asc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SetAgentModeJSONRequestBody defines body for SetAgentMode for application/json ContentType.
type SetAgentModeJSONRequestBody = AgentModeRequest

// StartCollectorJSONRequestBody defines body for StartCollector for application/json ContentType.
type StartCollectorJSONRequestBody = CollectorStartRequest

// AddVMsToInspectionJSONRequestBody defines body for AddVMsToInspection for application/json ContentType.
type AddVMsToInspectionJSONRequestBody = VMIdArray

// StartInspectionJSONRequestBody defines body for StartInspection for application/json ContentType.
type StartInspectionJSONRequestBody = VMIdArray
