package filter

// columnMap maps user-facing filter identifiers (lowercase with underscores)
// to fully qualified SQL column references including table alias.
var columnMap = map[string]string{
	"vm_id":               `i."VM ID"`,
	"vm":                  `i."VM"`,
	"folder_id":           `i."Folder ID"`,
	"folder":              `i."Folder"`,
	"host":                `i."Host"`,
	"smbios_uuid":         `i."SMBIOS UUID"`,
	"vm_uuid":             `i."VM UUID"`,
	"firmware":            `i."Firmware"`,
	"powerstate":          `i."Powerstate"`,
	"connection_state":    `i."Connection state"`,
	"ft_state":            `i."FT State"`,
	"cpus":                `i."CPUs"`,
	"memory":              `i."Memory"`,
	"os_config":           `i."OS according to the configuration file"`,
	"os_vmware_tools":     `i."OS according to the VMware Tools"`,
	"dns_name":            `i."DNS Name"`,
	"primary_ip_address":  `i."Primary IP Address"`,
	"in_use_mib":          `i."In Use MiB"`,
	"template":            `i."Template"`,
	"cbt":                 `i."CBT"`,
	"enable_uuid":         `i."EnableUUID"`,
	"datacenter":          `i."Datacenter"`,
	"cluster":             `i."Cluster"`,
	"hw_version":          `i."HW version"`,
	"total_disk_capacity": `i."Total disk capacity MiB"`,
	"provisioned_mib":     `i."Provisioned MiB"`,
	"resource_pool":       `i."Resource pool"`,
	"network_1":           `i."Network #1"`,
	"network_2":           `i."Network #2"`,
	"network_3":           `i."Network #3"`,
	"network_4":           `i."Network #4"`,
	"network_5":           `i."Network #5"`,
	"network_6":           `i."Network #6"`,
	"network_7":           `i."Network #7"`,
	"network_8":           `i."Network #8"`,
	"cpu_hot_add":         `c."Hot Add"`,
	"cpu_hot_remove":      `c."Hot Remove"`,
	"sockets":             `c."Sockets"`,
	"cores_ps":            `c."Cores p/s"`,
	"memory_hot_add":      `m."Hot Add"`,
	"ballooned":           `m."Ballooned"`,
	"disk_key":            `dk."Disk Key"`,
	"disk_unit":           `dk."Unit #"`,
	"disk_path":           `dk."Disk Path"`,
	"capacity_mib":        `dk."Capacity MiB"`,
	"sharing_mode":        `dk."Sharing mode"`,
	"raw":                 `dk."Raw"`,
	"shared_bus":          `dk."Shared Bus"`,
	"disk_mode":           `dk."Disk Mode"`,
	"disk_uuid":           `dk."Disk UUID"`,
	"thin":                `dk."Thin"`,
	"controller":          `dk."Controller"`,
	"disk_label":          `dk."Label"`,
	"scsi_unit":           `dk."SCSI Unit #"`,
	"network":             `n."Network"`,
	"mac_address":         `n."Mac Address"`,
	"nic_label":           `n."NIC label"`,
	"adapter":             `n."Adapter"`,
	"switch":              `n."Switch"`,
	"connected":           `n."Connected"`,
	"starts_connected":    `n."Starts Connected"`,
	"nic_type":            `n."Type"`,
	"ipv4_address":        `n."IPv4 Address"`,
	"ipv6_address":        `n."IPv6 Address"`,
	"concern_id":          `con."Concern_ID"`,
	"concern_label":       `con."Label"`,
	"category":            `con."Category"`,
	"assessment":          `con."Assessment"`,
	"datastore_id":        `ds."Object ID"`,
	"datastore_name":      `ds."Name"`,
}
