// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Start a collection from RVTools files
	// (POST /collector/rvtools)
	StartRvtoolsCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// List available datastores
	// (GET /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// StartRvtoolsCollector operation middleware
func (siw *ServerInterfaceWrapper) StartRvtoolsCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartRvtoolsCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.POST(options.BaseURL+"/collector/rvtools", wrapper.StartRvtoolsCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.GET(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963LbuLYg/CoofeerbdemfMml53RO5Yctp9OuHSUu3/bU7GRSEAlJOCYBbgCUo51J",
	"1TzEPOE8yRRuJEgCJCXLTrpP/nQrJi5rLSwsLKwbvo5imuWUICL46NXXEY+XKIPq58kCETGlCbpE/ywQ",
	"F/JvOaM5YgIj1SKjCZL/R6TIRq/+MYopISgWKBlFowTz6p+fopFY52j0asQFw2QxikZfxhTmeBzTBC0Q",
	"GaMvgsGxgAs18AyTRDZ7NWLonwVmKIkoQXT+uhwS1Mb/9u1bVDaVkCjIqlnp7D9RLEbfIo3UlYCi4G18",
	"Yko4TdFEj4spaTdBjFEmfySIxwznutWo6gJUC+B+biL/LRrxEoLGOAVjiAhgIAFxNa7pEm1JbdlrvIKM",
	"wExi8g8Jch1ZTZWJM2qgyVltsibpDZw+4lt+qeN8DdkCCSA/gjllQCwRgHKZdoers+qSoV0cG58auEUj",
	"thKUpurbGwJnqUSyicHl7TWlqcYAmUYlXDNKUwTJyMuikYfnvGyb5ymOofz+DnNxiXhOCUdt/oRVQ/Vv",
	"LFCmfvwbQ/PRq9H/d1jt90Oz2Q+d0T+sEFthdC8nNVBAxuC6BX5toh6Qy0Fb4Nbo2CSrM0LffpIr3T2A",
	"auHpucomtCCi3fl9kc0QA3QObqccsIIQTBZALDEHDu7VkJgItEBMj7kV7W+nvVQ3WNSpYVHQE/esxe20",
	"vQrYw9O3U3B+NpzUt9MAhRsIYLkzVEsfnKdQxMubPIECvfkSpwXHlIRPH7xgCiXVNPFtzHIQJT0REBRw",
	"JJSUgWkqF9azTyUZzxMeIAmXgxQKxFFULXGLTLVl3Py4yzB5fRwleIWiknytU07DGXko4SUuIvEyg+zu",
	"svAcbDFDUKDkRBF6TlkGxejVSKI5Fti/dRLM767wv9DbmUMBZxskhYbqCsX1QWkxS50Ridppskd5urbm",
	"0ixaDoGJ+OWFd+9hgfSsfpgyJJY08U6RQ8zeG+Zuf2QoP9sYH4645L7zocBzWrAYnUEBuaDMD4lQx2VP",
	"myWjxWKZF2J6mvNBwPr2aQW+Q502lG2Y3GWo8UmdKVqAlusTOfzo4+UJzOEMp1isg7qcbWH+3dT00hTF",
	"QjNbl3j+kBs8qhnl/HPKUAy5QNsOgAnPtwegsVgVNu7ANSjbRGyO4dLLS/K0kCP9hqAomI+mCeM1DWkO",
	"i1SMXs1hylHUEKV/XyKxRAycXV6BvTMsOXdWSLX+EmnuAlfxEiVFitg+wNxqVUY/xBzEGhqv+E6YUtdq",
	"UIzeU9I8OV+N5PSwEDTTOkJNBa1msErob0WarsGJbq9UvAvIBIbNv04hKWA6ivScn7zqP2Vwgc62oNiV",
	"7qootxlhvoUX9UbgFP8L+q88MSVznCASe459ueVBTFdIwVS1BDliMSJC/nXvaHx8dLQfgRimcZFKIgHI",
	"wWpycTO+R3ixlH+wY2iubYiqDH7BmVyD46MjedoR/a8jj8SN8+IzXC08uqCBcXJxA4oKXQ+guwAhg1/a",
	"IEz1GE8EQv7ryzYIv74USzsfTp+CGhnKuhckQxll6yeAonNNngyKQcvyBNA0xb/ZNxXvVIxcLWKFQkXS",
	"yBUQ3oNDn05+2eJqnS2BR7QgLvuDe8iB6VLDvktL9V1uKpCABFzgOXZFZt9lx+m+4aWnV68pRz5ZLBha",
	"yFtGm2haaPOuO2uCucAkFqBs7NM3f3Ty64uNPOG6cK1aqav6HqFgwrDAMUzlkRQjRvi+F39CyXTQFISS",
	"cXMaKECKIBeAEtSa0D+foAKm8tbZNoLJL4DUbA64uQCeMX2cVq2qM2ONmE3Mo4qnurlyQrMcMswpOcPz",
	"uUcHxBki3GvNuV4iUH4GM4TJAsRqOMVNVslSAHugdcjvVakoSdfn5KRPna4jcCE1jrLz6TadGwtQEaAC",
	"qRp/KHGviiyDbB28t1jrXuNEtSKDK3VwRsXSYR5+AM5Jgr6AI6k3noC9GeQoxQTtRwCrD8fyw+mBa9bo",
	"pkZbVn1TJ9C57v5MHUDVP+qWLXkv1CzU2nSI4RjIr4jJU4WDvVOQYVJwcLIP7rFYAr7OMiRkM47EWDYF",
	"MS2I4PKcrNjsoBR/YAk5IBSYNTk0KyKRDQvX4bzwhgi2bkusLQZoiaQtxnDFzMbdGwy9AwHiv60qHjZM",
	"0L0vui3ejS2xIev2Wlzd4TvApCxkiAh4jN4oN1GGOJcq3b08bbXnRN3qVJ9Ov5GVlwzBZK2VMOVAUC4Q",
	"C3TjH0DvGa7MOYzXPmshrOYd6j+qIa7/e2mg8X6cuCAGWjhwN1pMNexdTfR/L0rUuuYwDi5PgzeaCBv4",
	"tXz7yOPqSAX03KBLMedKuQNwQTkWeCXvApBwcKoEWEYZOvBqFs7x19S1CiKsRsGhwHy+Lh0Z1XmMCTgB",
	"s0IAQoX8x2nHLKcPmeXUneWkX6PRZOunujqNW0TPzV/9Xlb51ehcXnTl94B3qKmvyaY8rPMNUfiUc0Hp",
	"fJiDFHMR8C11+Sao6S7BOQBvslysgZJrWsIohNGXGKFEt1HYHQx3ZHhPh5Gm1MglmAXUu3BKP33LaJEH",
	"nTsNx2AGv7xDZCGWo1cvj462jiagmcQzF+sog19evzw6UgjNcWoMuRkmdprjh4csKB+OmsFeIx007P18",
	"1/MpzI4VZn7focE2sDDqOgbT0GFWMA8rryaICMTAzeU7fWEph+FghlIq5QD1nWYFR8x/w7ZDli18nluY",
	"+i6X1lDqQgEZAsozkZTmXYZEwQhKJNQH/d56ibgDsJ3dR8Waa6Z5PeJ3537v05whNIE5jLFYvz31O6+W",
	"kCX3kKGTOEYpYvKSN6Ur1wXkWMGXlItzD33Oyxu3FDuSFLKllA8MGXltEZCqCBQCxkt1WpIiTbVWKliB",
	"fNd1mqA04D6jgsY0vVYfvgYt4ud0QskcL4rKh9elx135e1mp20dPEYJmhUjidUQ2xZ/82p6stZrliJFl",
	"gfBiNohlqdrJaWdIQJz2O8GGSvlI9VTAzwa6OiXGgxsTCM/QCsebQkVC7lnDPieyYWCDmSbTII+aBreh",
	"ta/4pXn0/nYVgffyP7e3NI0AZeDD9e9vLnvtgq5kq5G8JGfnql9AzIIHqNzUXiTCNNyJ89mPYr/L2Isp",
	"SpFA7+AMpW9TOoNpuu6IfJrPtVrfE8kjllCAJUyU6Evl2IChjK7cmC1HRqgWfmuW7qzGu4e8PUqAJHrE",
	"qALYh/obLnAGBbqExKfXzhAXE8h9HjkjBIGeHeyhg8UB+Dg6Xj4/yj6O9n0nKfqSB0gXGu3Z8vhlaLR7",
	"yjYF7vnyRWC4Bu1KvB2g3Rl9pPzNeMHldglHfma55LXksiDcf1iEY1OCW603ouR0LRC/theEAQEiZaeb",
	"PKXQxDztKLBEhUi5poUcaRVTTwuNVmoi4ZTlwBBNCS8ij7EOI8LQ0BVJjdAqeK7kaPPYlPpiu1N2sY9k",
	"HR/n4F9fvqP3+v4w4OiT7W/yfHB7xMUFYsfXvcbpusTQhtjB0T/RKEOQbNQ8wZt1wJu07tw5HMr1Ky/m",
	"Hm4XyRlabRv65HKTM5NDohr6FWoVyWsgRA6PuOvvrm0X46Gg1JKQDjd6euSgR8VqSQFrYLT7/lOfjHZ3",
	"pX9Lqav/bkIQu+KHP6gfMAULOV9fCHFlBaiP8pv6O0BfcqbD4cBefrc41M3B2dW7fXUYKU4ZvRoZ1/3H",
	"4ujoOXoN/v3tKYAksX4I8Br8JWc0+ctQV+kNwf8skMFgG1/1W4075nkK18EoaB3QugHpOzzcHQYGBUy3",
	"OV9hOpypNSt5+Nha/nqseh32up7DxwAahW1gQQr0YD8YZ0xWiAiqrc1dPc7Lho9Cmc0i3m8xEwVMpzBe",
	"YoJ6TYyaJHqKTYktr0bvkbin7M5nYpQ3UM91QXcA+rvaMgATjhOkrgwLdd/ybd/cY2y5ADBJpODwhjfA",
	"2BORdDKxfQDkgCNEwGzdPTWpcPTjopCYM5p1j5MzNMeliTI0mG4FUtUM7E3Ozy5rwUiYiOfP/Jb91hL9",
	"jrmgCwYzPV0ujyh1E9EmpsaKQe1BaRoMWiadSgxkmNzCtEAhRQHlA7Z6OYjpEWlIfCz3O/VdxuO8mFCG",
	"OiN2Jhc3IFaNgpY2N3InL65ofIdE75jcNBsyascJVJ09Vaypuvj4+FqdgVOPn0iSx0a3YQKmpw2+UdeX",
	"fjizXiNORlWQeZHnlHlvts142tWU6oAkDrjtVbpTlIV0TwJ/teYCZQelYW19YGec1mfc92eWhI1Lq8Eg",
	"bw1qc4r9frt3abcMWyHPyZzBcJTaBWLy8hUrg/6GuzfOiw8rxCY0y7DIkM8RJ1lctonLNuASCkwPwKQW",
	"bqwODnCSplQJGBV+zMEh0H64i+Waq/CtidmBA+4opZl8+NFX3UI9yMqVu5C3BKmcG5tWkmCtw17UaBuk",
	"XLUqcrThgCmxFYBJrqCJE/cL6U3Esdr6fWt6eTK1QmKbpTVd7dqaf8IVxKkJVhliotaH3XASWj3Dg7X2",
	"D9SiNps0DGhb1c7hHTrZ73atvYrZzpbP5/vVU7eZ1yFgbaf4BYhKWSnzix8aQ4N6Q2g6YgJwCQywF9m2",
	"PWxbG5g3kKaJvqLgRTmX9/NlCYD388SByt+gAtX7vSMGBnWtYTgMKkD2sl+L2r12hy5iuhE9yAYleb/Z",
	"0eVeSZK73stLktw5sngTAjl3tUb67dBrnM6MdS5zzVt4+aUTgjOjRnvPaze/qzOErtH8WxkC2EgmGjCI",
	"20Nda41C0X2llY3kqlWaRefC6YgC57La2XraXlt9AdXAeenLeYH4KUPwLqH3nmQHmKwwN8vc5aFSEa61",
	"6PIT0xNgOUcglF8HoG8+eBm6Hh48IH/7RtbyOTwsJvog9lrv+gY/rzp3THEPmdrfGw//d90xOHQzTNSS",
	"v5qyjl9ULX/7eKiYaGpTuRU3eXiIc8S5VZtah1sctt5gv1u89G8OdFpW89vZfGiEjS4rfo9FvNzMNW0d",
	"7/Zs4AKSBDJTDcQmj8p/2eGjUUHKy5HXGbVKIQmECqwyHjSD+SNAghUNfOm7bfUmVFjE3vhM7JIb0rSE",
	"KwR4MZ/jGKtYRoZXOEW1KETn4plhzjFZXFStWpNd5SjGcxyD1VWugoGqIbWTGzIEzDjbRwxaXH3EuoCY",
	"ddFp+3CWbn/SYwQ+bOqT7Eu/rtMmGPaxmUvIG0rSt4Jhv84FozHiHuXP75qQ5LExaLnp6tuoiPkzim71",
	"h94hfCEpPvAv8WIpOP4XJgujmHRkHVQ3qi4Ct4ds6DoMSRH12SucG3BXTUtVayAa3endus3nwPlgPwdl",
	"cz09fIgHvErRHtjaZO4ObG0ybIdYcDC/G+zvzjYA2kk3Hth6ONDq2v05Z3SFJfej5HOcF13WgVpbifLn",
	"u9nWc2ljyudsFjI3fI4HnpwO3zW4zBkmelBislrfGocGydeNaxclfVvwSkAmKv99UFrHlMTK7hCvAyV0",
	"ekrslGVWeMijt4vjoMriO976bFAkqWwNQZKE8xum9BLNbQUmY6b5QUow+REORTS3eGCBuPx2vWSIL2la",
	"rwby/KhZCuQdFJJjgLDtASYgw2mKOYopSTiYoTUlCbhf4nipzkbjpDC5IJirAoM4QUqr1AAo/TlQPuCl",
	"98bZBrxddsVWV4lbtVemtthKNY6Dka0Voq9OVu93R8t0lRWfao+2LapyfvgBTCgRjKbe4iqJq8O1dGxT",
	"ouHD/ALBu+uyslENjF9bq3mhe6kkIgTvQFUSaUg5h07nqrYXNRNtMkxcb8Jx9OdJvXEmeZrcm8aE9eSb",
	"wHp0WAJV2ctGtbCiwIk33GCL4I+gvTAqp/4UhFvFYd9OeVB0w8RbR1DJa5i4AdcqHWjXgrtai6bMllhn",
	"JlHGC53+7AA4ZzR7UhB97GJNloF6jb0RWb6lvJ3qeDYdG8eHFxJtZq2a8iIJEroeL2zU2uQbmAiijpIm",
	"Z41CJtsMrktyTKBAC8p8Us6ZRbcFcdV4i6nUVhkyTaobbjJFUncJhtalbLUxwfx6uvXj2ambuPrIHPVX",
	"ib2d6v5d+f0F6Y5yKQ24CMZLs4H3uDIusAQxALmhs1Z/9kcbuazTvrU0Y2tFXqQqsKXgaHuKpxVFFep+",
	"utlKeR0Oh6UbXNXp/i8bdof5qU+/UVavUDGk3d+xWBqTOu/u856K7uEDKcge2HoBCc3qp3gwb+QLFuuy",
	"iKFRm0KhG13LYG971xgxWwLmW+ThOzuR5f7ZGpQ1YEEFE0jRCqURQITheIkSvUt0uIScC3D8L1WqTzc8",
	"AFdFjhhHCeIgcaY5XU/KMZ1c2Yo2bnxbt1utzbXmllvNILF/cgrCmFGusL4bOwQUGDEud3NiYzCRTrNQ",
	"ld7JAhNTju0an0bg+Gj8TP96djR+qX+9PPrrNT7dP/hIfITTmBuDyZaUe3v6gM6WWDsmuBfR63XeHdbU",
	"N5EcoGcSL89uFkrVjpB54AYEe0evbypvVASOX7+BfB2BZ6+nKMFFFoHnr3+HLInAi9d/X2KB3qZ0hfZH",
	"/SjmRd/i+fAbuBkmFzdqA4BZoUJIdbpeBD6OjsYvPo7kj5fjf9c/fh0f/6J/Hf+38fNn+ufzZ3+tJfWF",
	"0JgqQ9sjYqIn6EfGh8Pz8S/m+y8vx8fPDL7Hz34dP3tpmj97+cswRN/juNztu0Rztgbvzye6BJaDmAHV",
	"AGnw0f97EQIYt6MYOi+XjebfnGrk7nk/yP7YcH77EsAdAm4h8Yh7yl8iyDcpGtUPHeUPlTSt5aD8nMzp",
	"tkLT9PbJynxnkaYMZlsfQX265iBFc2MtUza7WkKGkjPM7/jAjPEVqkeIcDUCME6GTbTUeuE0qztZSpan",
	"uqse1BcswMm+vedVZfUlrir34q2fHiPmic29eDMdIxLTBCVgcgJkIzyXVzwEZgVJUm3TXSGGbQUoBGw1",
	"l+t3V26HAzAtRKHKZyP9UMMKmfJ+dzi/TvnB6OGGObUSOeT8nrK6Ya38Y/RodX8MHqHqqnLLN4miSWct",
	"KZgrWuQokcTiunDWDKlXLARVIwCYUrJQ6Ul6zcD//d//R/NsTLMZJnokXe+GgxdHRwdATS9JJFDyCuC5",
	"7Yk5gDOOiDCFR6vHh+5wzhWoNfD2ZjC+u4cs4bqUp8A6PGH/P+qDKr+Z5JjGsHowpEcuuOYXCbhDD4mN",
	"oSMgCCUVCXTlqrYdvq9IkRsAXjA8eviKyxm/NQoaPQ5P9ZUlKpn6k9zn9WDVdhWJtZH+AyoIZImnbnWW",
	"vAS8yGwERmGKEgAB2Qym6UbRHNdLBDIo4qXkAhuCNElVcJPt1BfaUbWT4HpFn25hD9VG9iUWOi3Bk0aL",
	"1XbKsABXv594U2jx23D3m3Ow6B0hSBr1RtUWRKjwqYPnJUw9K7Mr4KUROO/YZb0p2rXkn/bzAY6VsuuR",
	"mVAFvcqOEcwnazNzlWTcjkjikpt1A+30u51qvtzQFOx9VKlGZHB+JoE2ksnv47H+8okxrva9VeWkL9jS",
	"12XJs1TqDgLkkj+4QAlgiBepCITmtnMyup1Mjfb2KtEPsbpBgDktiONpbbBjsDKPZxFvOGLjBM0xQYk1",
	"zlbjTt1F7PYJ5lAIxOSQHz9e+ZZnJ06gpuPQJkl5MoP1LXZTZu8qon4tFQispXeDOTF3C6tLAk6vbwOx",
	"pd6HuIY43u0Gw1yrgPLwUGnK5ZjeGQNvkNURCEkUSfzUm4zSTQ0Iyp5eraMKsvs84MmU8qWU8RjoMiM6",
	"5AkcAlvZ6HPt71+A5I9BuWs1UEKvkTSf/oACZPAL2Pv/9//DKoEqo4rQWjOV+bwVFN6XLzxQ5L++fCQo",
	"bLxfy6ByVxv8cSYPP0HSfuzjUdci+AqJH5DdLoc57M7PhhSmtDq750QwhUV5oLKo6XnlTzqz4+pkQWMv",
	"U/drlHwg1c/5PAK84DkiSS1ZurvWnQrXqPBsAFPF7tZUI0fRKQ+A2gnar7MFi0Buq7nFtXdfUeert4aU",
	"5dupUe2B3ghQli8hkb8wgXGMOMezFO37p2WIXyCm6xv4RYZqozxXK00DU+ZgSBkKZXI5mc8xMa6BhoGj",
	"TAW/uNHRht7TIMdE6hf1SJYBc3tS3DtLTFv8Jhc3fBh2D1W4PYU5h5dz0WU9vXEL1tS2zahScHvGVCrG",
	"NU0RgyQOv89rtY3fZHNQtndC/Lwn+hyz7B4y5KsJpb8A2QnszTDlgDKA5tjL0XOaJr7VKCOzgG4BGDK1",
	"4H2jqKot594QKwWL+g4+XPWUiVLN3vtrRdkR5kWaBhlk4VTV2aBQk1uLJ1BpwJPhffXfsS5p0Uka2aIL",
	"Jfk9hM4mNU/agmDg9W0zdnfDpOUNTd+m8hNTSSiAZM5wBtkadNcc0tetLfdh0PPxJ7+L+UrZTMsqNhla",
	"QG1KGySfu+5j1b2oxWoxJGCGzMUoILF+lJvYmVNuzipzoRu9W8WKC5T8ftsrx3VDezRaJbRHmhMcb8v2",
	"788n3qTC0iPT8cSEbGO1oy1UTBWcLdUlX9TiO8x13LhtUoVj2nJA9T3WhbJN3vPWhFTh8Tfctyg2dj6m",
	"hBcZUskIvt0QsE6Eb+Mde6H/Nq4e7TfFHSoLln8Cc35eyy5y6Kq6h6c6LU15aLz6OIQLmKaw1I4Lrzgu",
	"hhdLuM2cPD6t7KvVUgHiviNshRhX3rWidZxBzvGC6KimjgPsSW5rHaUk3VuUs9vaVxNHj25dIBwhbrVQ",
	"Iw2G3KlsjcD6neoOE1+1bF0xUCuFccJoFoF5SvN8HYGCzyLAEcMwjUAOGUxTlPrvlH0wGStGw5fj48jT",
	"ghtoeMxxJDkgAhwKGAGyygLXL1OGPmAosZ833OZznHrD78/+BuQnkEOxtA8eerJsKvDu0DqorylfwB1a",
	"KyeyGax17Aw5ocs0phb66onoPWtCJ0K/nafENxGfQ38nlFSfvFRnSdYlATHXMu8S3gPDZVOY5zUp5Ug/",
	"HZrQLVIVsTC3YQwzJO4RIiArUoHztEk4PvBB6ZAia/wXvjgDFS6+7i5O0ThylpSZuGsr1MpYA+P18Jcl",
	"VIWi+nMnbMOogs7C8mkDnK3y3mOo5qDqYlwyvP0soXHmbKu4txbCF4Teh5m/JIm7gjZRb1KVQ/l7WQ7l",
	"vFYO5aQqh/LG1Or6IJlzYKEnD2gm82DtTN7RqoKro1Ed5I6GDjYdrSyiHU0MDfpqW+vzHyVuVWsdOxNT",
	"ItAXoapOMxTTLEMkgfa5xS222OAHLZzN4g7Wv2W6K0L/gd5wa+zrMpxBCiaT6uh9060hah+pkvKqLdE3",
	"qabcvhN5KpklyOPheH8+MU/Mdh3MnnO4pz7yVqWQOwxJ/SJQZ0IGMyA3MYPsMZSnMEbyvq1SiRbmy/7j",
	"Jx4SKmYpJHc+g4ffhODVIqg1FZTWgz6LwVbxe95l8V2GfLn1j12bRAdV/NmLmWyE5WNWP8looE7NsIIo",
	"25dC2awISqBaTlPPpNpXmNm6J56yJKGCJD5M+qqlOPzaVzrFWXRfHZVPgRSfZipQa0eqE0e1Oh0U0XV9",
	"WtmLhfZoDPEyZ71hR+UD+9XAQ0K4DejVFJ86kp0ehQrqgyk7tztSBGLc1WTKvoO5nbSHTHbCqIblp87c",
	"Bk/Gb6Bgv06isqlCjfdermw9dJ3pkyMGLlECfocC/G1yBSATOE4RePHs+YuXvx47dUVMvLGyHOuK55+r",
	"4oGqyG9WECzWtb/KGxWG6eclJEnqfxmnBBgl/kc6i3zBYIIua3q6pyC2/Y4S8OEKmF42KAs4pQ7lZx1C",
	"rd0FpmmiajAAt1mvWm8rMPnKKJZPu5sqngo7LNQLOCfchBeWCTNAB7CeXJyPnCjX0eqZ4oIcEZjj0avR",
	"84Ojg+dKDRVLxQiHqiiFiszVgQDUVlM8T0avRm+RUANfWesqM3cI1fnZ0ZFRAYQZxElGP/xPrumsVek+",
	"RdudRuHsi8/lZeDjSz1109krECMwBRyxFWKmQLXKErBiQmIEoDtYNNKq0T/0HOpemBtPaZ0YV4YYqgSP",
	"XkjExSlN1rulghy/LA1VZxnBCvTt+62CKigULyFZoESuwgv/KqiHewGrqlu9OPrVG9oyT7GWU1sv50QB",
	"Y1Y00wvTXM9v0ejQvtBvstG8zC7vyBOn3SPSuZqmdjH3kNw6oFwEHkIwNR5M09qAFc1c/FuUU5hAhg6/",
	"wvPk2+HX2XnyLUhN/XY8qhM0hwxmSBfW+EfLlA45SpUftuwDlF8CE5VLJJbWbfFqBNUDv/WNETnEb8nd",
	"NvfZp+2BLhU6ZNbZhrN+ehIWqlApM7fbfOTga5hB27JyxMYO5nCxYGghtVJl3UrwfM71Dn7hCR3B+hnw",
	"qjuhQoeZP2xTa9YB4p66bKrylGySlRfQB/Dx4dcEZ4jIc3MTnj7D8/l/Pb6OvJlFSDAcSy3IkNc/V0nm",
	"zhmt2mjNZ5mbz0koGWe+UiJhAC8qGybYOx7PIEfJ/gE4kdtPOdRLT1K6lihQkq7PyYniLf379MDi888C",
	"KQusQchY9irYy2iQY6ee3LFPq++6MKjASKlfK/Or/MFxgjpgMJGtFRydcz+1aFIbxSOXLuACE/WmjEFZ",
	"qdZyOyNWeszEsi0MbLjYAq8QARVX9aklZUuwUg+OPbVwO2M4TUFC74mSZ11YezCGLXyHyryvOPl22Cw5",
	"FtSDTtyGPfJt0i9g8I9zbjqYDdW9fBXYwqfiZNcco8DwwgAwAdDhEVf5rZUF83ODrTt2+NX8kudgI1wm",
	"dC301L1+cjZpyU+b06rr2NqnzxOaQUzG8fGz5x9H+4AysEAEqRC/suRdCKKSMJ2AVaGT/3PPzvbxY/LX",
	"/2W6j/9xNP4Vjuefvh7/8m3/3zx2gcfk+I6i6z5F0VCkmXxSvW1pkhzLd5kAqyYAuoR6rxSuSlMDY2Hb",
	"ZDtFgFB3fjVnJFe2LGG4k533FokSWw9ZZus6/9i95xA8tPXQF0Wm0AZ7oz5P3I39vffWhGYZHHMk4ZBE",
	"1xgAHtMcOaV+6AqxFUb30Srjkc7x/TjaPwBnWilStUCrVh9HIa1KjTva3SHxL/12bDVcadidYQLVzM0J",
	"Wlvjf5xfAMjiJV6pIBgBsXq/ZnJ1qyKseC/Xa6Se7ODQXOSqMGojQ65AdrDZTImoUruD6sNb+3Lz9+Za",
	"87S4STafmXjpvRhyNMaESx1KYPXMy0wPoiMK9gNcOVvbB0eGg9C4eigvvQ5EfrLbhEHf3iY2uUSU0z87",
	"CtbKfur7RfuN8w7lzXBr39acN9+gf2L9DqapXaawUme2Vee+PPyq/t9lmnuL9Ab9Afanfjs/NLrB5GFT",
	"XEkZOMcoTUwN2wQzg1V5asn5XkEe68pt5lB/JcdRh9etYRE1BmQ68T0CbtZpZFUBlZapvLSReRc1MgUY",
	"IhDnxQ2HC6TbmJ8MZuZXnBcnq4XqdrJayJMRfVH56U6RYAmlIZCCb/RJtspTFU9rXhv1HadS23DJNrzK",
	"Bhdr5XSSB+aoW7zJG2quL/SacZ9Mwil0thJw31eKdUkwvTcSHXmjWbcZMTxARlFz+u1QJdbjzdbg/EyD",
	"hQX3BTMPklq1IvshcXXulNH/E9ki3HcDPBZ7hYqyTpbNBq132X6Hax63oTEGKe9JZTFTb635F97ESmZO",
	"SGZQn2wz1w+iWM7WrsoQUhrfuE1+Hl0/j64/+NHVEVveoYl7D6/+AALgbPWn1cmbweZhxbyJ2jCRd6gv",
	"HWOadxvk3yLReFTkz3UMhl5M8fCSEbuWYk/GDypsaAVxqkt1uVBoPxJ/ODdUoe1hLiifAvlTLX/jgRKf",
	"DNER/Sb9Rr3Z8bRrn6p40dpzJC4wD178r6us58reyub43ipQq9SifxqJ2I/Da756Th5+a+CWVLngA/Tv",
	"ZpW8nXFhAKodMd9Q19/t9Mfy+jWoYh+x/CNwo7fegIcbp3V33HBuLHlP8qWnpFytVMxD2bPmG7M16M0t",
	"kdunz1W5jEH8Sk0Aeop07YpGNK6g+aRs2FqkMFmoeuw9z9HD9qOcH8QOAA0PCtUppkH/uW31+KHVzanC",
	"tgbKdhViHTcHDNEnEGotIBMdq/vsOxDHVBlRYfoPj32uIi5ThmCiij3kjC6YKRDzAL6ETITuKS7tazvt",
	"kK1U4RUVzRBekkvdqr4yoTB4XecAMnEo799jVcGyti71nBTtQnXv970u2p5sXD2iP6WiL6b+R+Ww91T7",
	"msuC/0/EY7L1sSdt5lbX4lFFOzBX540tEdXHlzqixI6gF6uDVetPaVTHQjOPJ6MrxJXCriqcJGXVHGeE",
	"KphFcuUMcnQwihoMf6ZmcF/wGHTIOJNoGB8YLqjGsKjENWhKUjl/dc6cJmF04HRrJJAhAZUusHdz+U5F",
	"u+4fgPdopd2hlCP1PBvTlcYYsO8fHIDrpSoIluQUEwESivT6M6SEIBSoRnK4gJhwYR8eaBNcnopd1N7h",
	"iVhO07EnKwJVZ6JX3XpPa3hqAj/4BG2vU/skbax7+RJ2TXc0a8G7FiMCiMRsnYvSzszvdJA0uEPrSIVB",
	"K4C4rSCU0him5e4BUBdxhbGKpnCBRuIAnKj4CnlQEAEubq4BXSF2z7CESnbLGVphWvB07WH0NqNcFC1G",
	"2X0qlucFnydOxtqMSzmwuy6plkux4TMtuL8LTDFDHoi6QwOd7pSBgjAE46Wyu9k6ag/U2xnynQnBjdU4",
	"fQ5jmEP1CA+uea0aRFii+I6Xr6zkDK9wihbIhHGnKSh5moO9Ug+L7PMS8uecMhRDLhDbN0/3eHYHuMJk",
	"kSKQyo1np4vl7DpKUl2tFj3SduKi9JgsbedZd7BP2cZIPOUbKYF/QjGs1rCkaQkBiOvUCnNNtYBdKou8",
	"SWo5aMoighki8TKD7O4AnGjVbexEuxZEe/JyhhTwiVvVza/LyCl+q4B5RG23miW8wqcWPRBDEqMUJapu",
	"n6q5pvO7dDa1wrxrvUs6uTUlH7TiCp5qXGd1HfL16ljmoeoSKV2ctMy3yyFmpSJurTneHdqi5iPuzSEr",
	"Z0tCVYy9C4PBBU1Tz5BB2ufeQtbqgsEB5GsSVysot5OUuJQo5TWTwr+sfgjkSnDfdoFMNPbL7jWMxiwb",
	"pXx/rw071ADiSOLIKibqQWe5/JG+RmAGUpxhAdCXGKGuq+wJoSoZq7bf7aV2F/teX057t31dprcUAT9f",
	"TmiWF1LTvV/ieAnofJ5SmMhb15KamIw5guqxBsWppaVUP+Y5NmmcDaYFWjtXL/yRRHYzdTmspgUXSD/G",
	"DwTNaUoXa5Aghle26LQqmEbZXYrnYuyJ7vGo3ZQ77HoBMWupDbvfJLVp1o9YFmFYBecaNB4DVFibwcgG",
	"eWAW3D5n5SLvLpO6EJplQmpLF4eXTBdWdO2ZVzUdxl/mGVLDqYaJJfPGlf6Hq9qQdeZ9f3IC9CsaTsnl",
	"viP0rELmKXilnM56GfuZpUw4rCDtsAO6afs2NGEHgehllEPi0msItyjBdPiVwAx961J4tZalVd5KpDf8",
	"RIplTcLGAbjW3GQ1BLlSmBSo1PoAngN9RmjpKKUqFzhNjUmiTyWWG7vPlSnb6PwRyC2clfKtTsbS8O/1",
	"PZoSZA/xPW527jerfGL23l81LRpxW2S/LNhkVHNver3Pou4hVjnGIB3eLGWlHVTOy8PytJ9jgvnyoRc7",
	"reZDwPXdOderP4TH5e2rVxZikuAVTgqYuiqLsPf9A6AjnVTleB1LpOvE55bDeiTZZdEfAmYipdRt0R06",
	"GGBomOMxfeGD5GapbF4WZBOhWWOkHRTJaYw3nD1UjEWX61rb9GvL2beal8XW8RO9peM9y+rZqhICx6HR",
	"7f7U0IZ2vRxqR8UUtHcE1hdr4FpJkde/l2OtQiXqVoq5wLGtxFDXyP/CXSB0jfEDcGFeDCq9JLZsxc05",
	"EBQk5hWXsp4rEDhDAHGBMyjQEKMAH35sCQoWSDQQ6ZcHP0asjMVa4+yRA9dLRovFMi9cDIOsOsVcWVQt",
	"nlWU8YM9N8ILSAdPDkiofaey0Iel1f7Mef2Z87rjnNf3zUo0O4mvN0vULizRlfoaChmaKE+Ts08eySCh",
	"5zHJextYI453ywrhhEHjctssRukp1lxTDkBA0L3JIbTO5CELX0nKeopzt5ZVZ4hOubn7XORBipVN83RU",
	"q/7V2HFWp9Gj9JCb7sdQiON3Jf3PXLqfuXT/5dPAH1doNFPBNz7HpdbZlhz6AZDvL7d3rzpozDZXHY6e",
	"SnUoFIA7Vx12zHeajFtqEGV4TV9uQfWe1+hRKwAYcMLO17KJm7bgJXvVUoVh7sQvSvMqIqmW32//1qUB",
	"NLHr2cjnRD91c3t29rcqKtWssF2CgFDHuu9tktz5rqrVi3qffpzV3EmmBW4OGFqkjrD+Bq8/UqiD+2zf",
	"dwl1GL48W+R6gD1Cwe2Uq6g7ycE6/K6Kg9gPhjdUPLH7mIYEoXIHq5h7yiSUAS6pScjDldxMnVVZTEu5",
	"6x4/QEnOclF5tHx5cq7g6DqdVMMiTylMdhCq7YzWuwkLDykvijopd51VM6zcYTt3ZsvUmSdfcXchO7eq",
	"bB3chTd6AQO5Mi+On7e7/IZTBASlIIVsgcBeBr+AX15MT/cfqN8oQBRqArIZTNPO7TqgfpLWpt0qSj9+",
	"TaO2EvkYdY2cakZDri/tukblYzsdCdOmyWPuFD2Feu3Jt030ZzegJvguzsrT1snYNbgY5Deo4aR5cMNK",
	"Tj/LLP00Df0ss/SjlFl6HDdQs8zSIEHsrxzQLGwxgyJejrVZY6xeUrWy2n8bOpXtXQPU7fRN2etxrkbO",
	"lOVUm1uHGm9X2IEey6Lz8JVXaBvwnPCHco2UpKheyp/yIZaeYUwxvOqW5YFm7a0/UCWsnS9cfyWsXW7g",
	"/ppYdo3Kylh/lDpVj7My3XWqdr80h1/V/wd7YhWB3qZU3mp6q7mqxrWoxbpt3z6L/2NEKFk0HQR7WQUw",
	"Va9gIwG9NYPo2ggAasbQvCAZZmvpOsiHo/DUJqfvsdiP5caxaD30rNZo/7Dn9EmiSkcxD+s8zuncXwjP",
	"d5HsY66fteo67CpPXK9u20NokLT5gdjiEWpS1MDVaD9U/jRI8Hgu4EfhMuMLboxdmcB3LZeG1ki0WukG",
	"lRJ/ljHsZaEfpIDhMAHWeAVMTqZm12tfsHT0anQIc3y4ejaSy2P6fe14+VzlR6pSWxkkcIEypJ6PNzyh",
	"37v2vdxVe/9J1evx9Z/Unpj2bHxjKHfyDqsaJq1hVNGwr/32f8CQTnR2hnCt7MF6n8BsTfDPAsmWAMaM",
	"cl35y9hdnSHbVrGe/afDS3x0emujq1vZu543Gh1HR7VQ9WckW5knref09MIb++5hfRtVw7oM5wMO5ZJ3",
	"HV9wiucoXscpUsNr56kH38rj5HlxsVVHx89abhWlyM/ifr+DXT7jdvj26dv/CwAA//8BgcKRUBkBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
