// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive or Excel workbook
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Start a collection from RVTools files
	// (POST /collector/rvtools)
	StartRvtoolsCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// List available datastores
	// (GET /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// StartRvtoolsCollector operation middleware
func (siw *ServerInterfaceWrapper) StartRvtoolsCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartRvtoolsCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.POST(options.BaseURL+"/collector/rvtools", wrapper.StartRvtoolsCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.GET(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96XLcOrIg/CqI+u4XLUWXNi9n7vGN80Mq+diKtmyFJKsnpu1xoMisKlyRABsAS6rj",
	"ccQ8xDzhPMkENhIkwaVKJdl9rv/YkoglM5FIJHLD11HE0oxRoFKMXn0diWgBKdY/Hs+BynMWwyX8Mwch",
	"1d8yzjLgkoBukbIY1P9A83T06h+jiFEKkYR4NB7FRJS/fh6P5CqD0auRkJzQ+Wg8ut9jOCN7EYthDnQP",
	"7iXHexLP9cBTQmPV7NWIwz9zwiEeMwps9lsxJKqM/+3bt3HRVEGiIStnZdP/hEiOvo0NUlcSy1w08YkY",
	"FSyBiRmXMNpsApwzrn6IQUScZKbVqOyCdAvkf64j/208EgUEtXFyzoFKZCFBUTmu7TLekNqq194Sc4pT",
	"hck/FMhVZA1VJt6oLU1OK5PVSW/hDBHf8UsV52vM5yCR+ohmjCO5AITVMm0PV2/VFUP7ONY+1XAbj/hS",
	"Mpbob68pniYKyToGlzfXjCUGA7CNCrimjCWA6SjIouMAzwXZNssSEmH1/R0R8hJExqiAJn/isqH+nUhI",
	"9Q//xmE2ejX6/w7K/X5gN/uBN/qHJfAlgTs1qYUCc45XDfArE/WAXAzaALdCxzpZvRH69pNa6e4BdItA",
	"z2U6YTmVzc7v83QKHLEZujkXiOeUEjpHckEE8nAvhyRUwhy4GXMj2t+c91LdYlGlhkPBTNyzFjfnzVUg",
	"AZ6+OUdnp8NJfXPeQuEaAkTtDN0yBOcJltHiYxZjCa/voyQXhNH204fMuUZJN41DG7MYREtPQJIhAVJL",
	"GZwkamED+1SR8SwWLSQRapBcgzgal0vcIFNlGdc/7lJCfzsax2QJ44J8jVPOwDkOUCJIXKDRIsX89jIP",
	"HGwRBywhPtaEnjGeYjl6NVJo7kkS3joxEbdX5A94M/Uo4G2DODdQXUFUHZTl08QbkeqdpnoUp2tjLsOi",
	"xRCEyl9eBPcekWBmDcOUglywODhFhgl/b5m7+ZFDdro2PgKE4r6zocALlvMITrHEQjIehkTq47KnzYKz",
	"fL7Icnl+kolBwIb2aQm+R50mlE2Y/GWo8EmVKRqAFusz9vgxxMsTnOEpSYhctepyroX9va7pJQlE0jBb",
	"l3j+kFk8yhnV/DPGIcJCwqYDECqyzQGoLVaJjT9wBcomEetj+PQKkjzJ1Ui/A5Y5D9E05qKiIc1wnsjR",
	"qxlOBIxrovTvC5AL4Oj08grtnBLFudNcqfWXYLgLXUULiPME+C4iwmlVVj8kAkUGmqD4jrlW1ypQjN4z",
	"Wj85X43U9DiXLDU6QkUFLWdwSujveZKs0LFpr1W8C8wlwfW/nmOa42Q0NnN+DkjOBW7VJR1lllfZAjig",
	"t8do5y2ZL9DxEpPEckAnTdBegVOkYeMgJOZSaEVGnYU5X5Kl0mYWTEiB8Ez1wvo3NMMkyTmE9dc2pvgo",
	"SUL+wOErU8TojMRAo4DaoEQGitgSOJ7r245tiTLgEVCp/rpzuHd0eLg7RhFOojxRREZYoOXk4uPeHZD5",
	"Qv3BjWG4vibqUnxPUrWGR4eH6rSk5rfDgMSOsvwLXs4DuqSFcXLxEeUlugFAtwFCiu+bIJybMZ4IhOzX",
	"l00Qfn0pF24+kjwFNVJIuxckhZTx1RNA0bkmTwbFoGV5Amjqx4fdNyXvlIxcLmKJQknSsS8gggePOd3C",
	"ssXXWhuClBpBXvRHd1gg26WCfZeWG7oclSAhBbgkM+KfRX2XJa/7mpemXr2oGPl4PucwV7eUJtGM0BZd",
	"d96YCEloJFHROKSv/ujkNxcjdUx24Vq20ifkDmVowok+PdWRFAGnYjeIP2X0fNAUlNG9+jRYogSwkIhR",
	"aEwYnk8yiRN1a20a0dQXRCs2C1JfgMCYIU4rV9WbsULMOubjkqe6uXLC0gxzIhg9JbNZQIckKVARtAZd",
	"LwAVn9EUlP4S6eE0NzklTQMcgNYjf1AlYzRZndHjPnW8isCF0jiKziebdK4tQEmAEqRy/KHEvcrTFPNV",
	"673HWQdrJ6oTGULrlFMmFx7ziH10RmO4R4dK+TxGO1MsICEUdseI6A9H6sPJvm8W6aZGU1Z90yfQmen+",
	"TB9A5S9Vy5i6VxoWamw64CRC6itwdaoItHOCUkJzgY530R2RCyRWaQpSNRMg91RTFLGcSqHOyZLN9gvx",
	"hxZYIMqQXZMDuyIK2XbhOpwXXlPJV02JtcEADZG0wRi+mFm7e42htyBAwrddzcOWCbr3RbfFvLYl1mTd",
	"XoutP3wHmIy3GTJaPE6vtZspBSGUSnenTlvjedFXQ92n0+/k5CUHHK+MEqYdENqF4oCu/YLMnhHaHMRF",
	"5bMRwnreof6nCuLm30sLTfDjxAexpYUHd63FuYG9q4n596JArWsO6yALNHhtiLCGXyy0jwKukkTiwA26",
	"EHO+lNtHF0wQSZbqLoCpQCdagKWMw35Qs/COv7qulVPpNAqBJRGzVeEIKc9jQtExmuYSUSbVLycds5w8",
	"ZJYTf5bjfo3GkK2f6vo0bhA9s38Ne2nVV6tzBdFV31u8S3V9TTUV7TrfEIVPOye0zkcESoiQLb6pLt8G",
	"s90VOPvodZrJFdJyzUgYjTDcRwCxaaOx2x/uCAmeDiNDqZFPMAdocOG0fvqGszxrdQ7VHIspvn8HdC4X",
	"o1cvDw83jkZgqcIzk6txiu9/e3l4qBGakcQaglNC3TRHDw950D4gPYO7RnpouPv5tufTmB1pzMK+R4tt",
	"y8Lo6xhO2g6znAdYeTkBKoGjj5fvzIWlGEagKSRMyQEWOs1yATx8w3ZDFi1Cnl+ckA4DrA8F5oC0ZyMu",
	"zMMcZM4pxArq/X5vv0LcA9jNHqJixbVTvx6J27Ow92rGASY4wxGRqzcnYefXAvP4DnM4jiJIgKtL3jlb",
	"+i4kz4q+YEKeBehzVty4ldhRpNB24zttrTby2iGgVBEsJY4W+rSkeZIYrVTyHELXdRZD0uJ+Y5JFLLnW",
	"H76GFBvG8RzO2ITRGZnnpQ+wS4+7CvdyUrePnrINmiXQOOjIrIs/9bU5WWM1ixHHjgXaF7NGLEfVTk47",
	"BYlJ0u9EGyrlx7qnBn460FWqMB7cmGJ8CksSrQsVbXPvWvY5Vg1bNphtct7Ko7bBTdval/xSP3p/vxqj",
	"9+qfmxuWjBHj6MP129eXvXZBX7JVSF6Qs3PVLzDhrQeo2tRBJNppuBXndRjFfpdzEFNIQMI7PIXkTcKm",
	"OElWHZFTs5lR63sigeQCS7TAsRZ9iRobcUjZ0o/58mSEbhG2ZpnOerw7LJqjtJDEjDguAQ6h/lpIkmIJ",
	"l5iG9NopCDnBIuSRs0IQmdnRDuzP99Gn0dHi+WH6abQbOknhPmshXdtozxZHL9tGu2N8XeCeL160DFej",
	"XYG3B7Q/Y4iUv1svutou7ZGjaaZ4Lb7MqQgfFu2xLa1brTci5WQlQVy7C8KAAJOi08csYdjGTG0pMEWH",
	"WPmmhQyMimmmxVYrtZF02nJgiaaFF1XHWIcRYWjoi6JG2yoEruSwfmxLdbH9KbvYR7FOiHPIry/fsTtz",
	"fxhw9Kn2H7NscHsQ8gL40XWvcboqMYwhdnD00HiUAqZrNY/Jeh3IOq07d47Aav2Ki3mA22V8CstNQ6d8",
	"bvJm8khUQb9ErSR5BYSxxyP++vtr28V40Cq1FKTDjZ4BORhQsRpSwBkY3b7/3Cej/V0Z3lL66r+dEMau",
	"+OMP+gecoLmary8EubQCVEf5Xf8dwX3GTTgd2slu5wemOTq9ererDyPNKaNXI+u6/5QfHj6H39C/vzlB",
	"mMZFbM9v6C8ZZ/FfhrpKP1LyzxwsBpv4qt8Y3InIErxqjaI2AbFrkL7Dw91hYNDAdJvzNabDmdqwUoCP",
	"neWvx6rXYa/rOXwsoON2G1grBXqwH4wzoUugkhlrc1ePs6Lho1BmvYj5G8JljpNzHC0IhV4ToyGJmWJd",
	"Yqur0XuQd4zfhkyM6gYauC6YDsh811sGESpIDPrKMNf3rdD2zQLGlguE41gJjmB4A44CEUnHE9cHYYEE",
	"AEXTVffUtMQxjItGYsZZ2j1OxmFGChNl22CmFUp0M7QzOTu9rAQjESqfPwtb9htL9JYIyeYcp2a6TB1R",
	"+iZiTEy1FcPGg1I3GDRMOqUYSAm9wUkObYoCZAO2ejGI7TE2kIRY7i0LXcajLJ8wDp0RO5OLjyjSjVot",
	"bX7kTpZfsegWZO+YwjYbMmrHCVSePWXAqr74hPhan4HnAT+RIo+LbiMUnZ/U+EZfX/rhTHuNOCnTQep5",
	"ljEuu+J0rQkRLc+ZCUgSSLhehTtFW0h3FPBXKyEh3S8Ma6t9N+N5dcbdcGZKu3FpORjkjUGtT7Hbb/cu",
	"7JbtVsgzOuO4PUrtAri6fEXaoL/m7o2y/MMS+ISlKZEphBxxisVVm6hogy6xJGwfTSrhxvrgQMdJwrSA",
	"0eHHAh0g44e7WKyEDt+a2B044I5SmMmHH33lLTSArFq5C3VLUMq5tWnFMTE67EWFtq2UK1dFh4YPBkyL",
	"rRaY1AraOPGwkF5HHOut37eml8fnTkhssrS2q1tb+ys28fcJDFtde6QOJ6HTMwJYG/9AJWqzTsMWbavc",
	"OaJDJ3vr1jqomG1x+cxoajobvd0e1n1zjmKggsiVDsl6ffXfiZZN4cW7OVd70UNmvPa1vdK5vpe89axs",
	"3LA80xk4Rbp0SHOUmCSBk/dtnmK6p27MOkzUtkN4ynJpXKM28oAUcyB3XW5aZdcKHILeuKGOQIgAOE0j",
	"4KaGv2D0UJ3Iep0uirmCny8LAIKfJx5U4QYlqMHvHYE/0MUp7bFfLWQv+jWo3Wts6SKmH8YELhIr+M2N",
	"rrZ0HN/23tji+NY7gNYhkHdBreUsD727mnRi7wZbNz0UXzohOLV3h6CS4ifFdcYN1pp/K+IeaxlUAwbx",
	"e+i7vNWiuu/xqpFatVKd6lw4E0bh3dA7W58319bcug1wQfoKkYM44YBvY3YXyPDA8ZIIu8xdbjkd1lsJ",
	"qT+2PRFRc7TkL5io+/UHL+L12wdvkb99Ixv53D4soeZkC5os+wY/Kzt3THGHud7faw//d9Oxdeh6bKwj",
	"fzllFb9xufzN46FkonOX/665KcBDQoAQTldsHG5Ru8mKhGMBCqfuQE9tOb+bLYRGu6VpKe6IjBbr+eNd",
	"tIE7G4TENMbcllBxGbfqNzf8eJTT4kYY9MAtE0xb4iOWqWi1/YXDXlrLQIRynptx0X0ZtDZgy4/jWuAl",
	"IJHPZiQiOoCTkyVJoBJ66d22UyIEofOLslVjsqsMIjIjUZGvWw5pPPuYA7LjbB4m6XANEesCE95Fp81j",
	"eLqdaI8R7bGuI7YvZ71Km9ZYl/X8YMH4mb4VbHdmXXAWgQgof2F/jCKPC7zLbNfQRgUeTqO6MR96hwjF",
	"4YTAvyTzhRTkD0LnVjHpSLUor5FdBG4OWdN1OCgR9SUonGtwl00LVWsgGt057abNl5bzwX1ulc3VnPgh",
	"bv8yL31ga5uuPLC1TSseYrYi4nawkz9dA2gvx3pg6+FA68v9l4yzJVHcD/GXKMu7TCKVtgrlL7fTjecy",
	"FqQv6bTNxvIlGnhyenxX4zJvmPGDsrH1+lY4tJV83bh2UTK0Ba8k5rIMWmiV1hGjxgwSrVrqDvXUJSpq",
	"04g2N+Y2joMydfFo47NBk6S0NbSSpD2p45xdwsyVrbJmmh+kblUY4bYw7gYPzEGob9cLDmLBkmrRmeeH",
	"9VIv77BUHIOka48IRSlJEiIgYjQWaAorRmN0tyDRQp+N1jNjE2CI0FUZSQxaqzQAaP25pWbCy+CNswl4",
	"s1ZNUb6lUbDm3FWoKcfxMHIFUszVyen9/mipKU0TUu1h3do9zvN1dvABTRiVnCXBsjSxr8M1dGxbl+LD",
	"7ALw7XVRDqoCxq+N1bwwvXTmFOBbVNaRGlLDotOjbOxF9eyilFDfhXI0/vPkG3mTPE3CUW3CasZRy3p0",
	"WAJ1rdBaibU8J3EwxmKDiJdWe+G4mPpzK9w6+PzmXLSKbhwHiy9qeY1jP8pc50BtW3CXa1GX2Qrr1GYH",
	"BaEznz0AZ5ylTwpiiF2cybKlyGVvGFpoKW/OTRCfCQgUw6uv1lN1bU2VGKQpYoxrBUrFGiaCcUcdl9Na",
	"9ZZNBjd1SCZYwpzxkJTzZjFtUVQ23mAqvVWGTJOYhutMEVf9oG3rUrRam2BhPd15C93UdVxDZB73l9a9",
	"OTf9u4oa5LQ7tKcw4AKOFnYD7whtXOAxcISFpbNRf3ZHazl6k761tGNbf2aio3lyAZtTPCkpqlEP082V",
	"F+xwOCz8iLLOmIeiYXdso/70O+PVshxD2v2dyIU1qYvuPu+Z7B6+Je86AFsvIG2zhinemixzT+SqqPxo",
	"1aa2eJWuZXC3vWsC3NW9+TYO8J2byHH/dIWKwrmohAklsIRkjIByEi0gNrvEhBmouZAgf+j6hKbhPrrK",
	"M+ACYhAo9qY5WU2KMb0E4ZI2flBft1utybX2llvOoLB/cgriiDOhsb7d8wgoCXChdnPsAk/B5Jbo8vh0",
	"TqitQXdNTsbo6HDvmfnp2eHeS/PTy8O/XpOT3f1PNEQ4g7k1mGxIuTcnD+jsiLVlggcRvV5l3bFcfROp",
	"AXomCfLsevFjzbCgB25AtHP428fSGzVGR7+9xmI1Rs9+O4eY5OkYPf/tLebxGL347e8LIuFNwpawO+pH",
	"Mcv7Fi+E38DNMLn4qDcAmuY6btbkKI7Rp9Hh3otPI/XDy71/Nz/8unf0i/np6L/tPX9mfnz+7K+VTMY2",
	"NM61oe0RMTET9CMTwuH53i/2+y8v946eWXyPnv269+ylbf7s5S/DEH1PomK3bxPN6Qq9P5uYul8eYhZU",
	"C6TFx/z3og1g0oxi6Lxc1pp/80q4++f9IPtjzfkdynr3CLiBxKP+KX8JWKxTKasfOiYeKmkay8HEGZ2x",
	"TYWm7R2SldnWwms5Tjc+gvp0zUGK5tpapmp2tcAc4lMibsXANPklVCNEhB4BWSfDOlpqtVqc050cJYtT",
	"3VcPqgvWwsmhvRdUZc0lrqxxEyw6HwEPBCRfvD7fAxqxGGI0OUaqEZmpKx6gaU7jxNh0l8CJK3sFyJWw",
	"uX535XfYR+e5zHVdbzCvWyzB1jS8Jdl1IvZHDzfM6ZXIsBB3jFcNa8Ufx49W7Mji0VZSVm35OlEM6Zwl",
	"hQhNiwxiRSxhqoVNQT/9IZkeAeGE0bnOyTJrhv7v//4/hmcjlk4JNSOZIj8CvTg83Ed6ekUiCfErRGau",
	"JxEITwVQG6Hrvdh0SzKhQa2AtzPF0e0d5rEw9UslsUXd/6M6qPabKY6pDWsGAzNyLgy/KMA9eihsLB0R",
	"BYhLEphyXU07fF9lJj+iOudk9PAVVzN+q1Vxehye6qvFVDD1Z7XPq8GqzdIZKyv9B5RNSONAse40folE",
	"nroIjNxWYkAS8ylOkrWiOa4XgFIso4XiAheCNEl0cJPr1BfaUbZT4AZFn2nhDtVayimRJhcjkDtM9HZK",
	"iURXb4+DecPkTXv3j2do3jtCK2n0w14bEKHEpwpekDDVVNSugJda4Lxnlw3mpVcynppvJnhWyq6XedrK",
	"BpZ2jNYkuiYzl5nVzYgkobjZNDBOv5tzw5drmoKDL1FViIzOThXQVjKFfTzOXz6xxtW+B7689AVX77uo",
	"85Yo3UGiTPGHkBAjDiJPZEtobjPzo9vJVGvvrhL9EOsbBJqxnHqe1ho7tpYjCiziRwF8L4YZoRA742w5",
	"7rm/iN0+wQxLCVwN+enTVWh5tuIEqjsOXWZYIB3a3GLXZfauyvHXSoEgRnrXmJMIv5q8IuD59U1LbGnw",
	"9bIhjne3wYgwKqA6PHRudjFmcMaWh9uqCLRJFEX8JJiM0k0NjIqeQa2jDLL7MuCdmOJ5mL09ZGqrmJAn",
	"dIBcOacvlb/fI8UfgxL2KqC0PcFSf+8ES5Tie7Tz/+/+h1MCdUYVZZVmOt17IyiCz30EoMh+fflIULh4",
	"v4ZB5bYy+ONM3v7uSvOFk0ddi9anV8KAbHc57GF3djqkGqfT2QMngq2mKlrKqdqeV+GkMzeuSRa09jJ9",
	"v4b4Ay1/nM3GSOQiAxpXMsS7C/zpcI0SzxowZexuRTXyFJ3iAKicoP06W2vly001t6jyWC50PhVsSVk8",
	"ODuuvGo8RoxnC0zVT4TiKAIhyDSB3fC0HMQFcFPUISwydBvtuVoaGtjaDkNqb2iTy/FsRqh1DdQMHEX+",
	"+8VHE20YPA0yQpV+UY1kGTB3IK+/s662w29y8VEMw+6hCnegGunwGjamlmkwbsGZ2jYZVQnuwJhaxbhm",
	"CXBMI+h9iO531RwV7b0Qv+CJPiM8vcMcQoWwzBekOqGdKWECMY5gRoIcPWNJHFqNIjILmRaIgy2AHxpF",
	"l6o5C4ZYaVj0d/Thqqc2lm72Plwgy40wy5OklUHmXimhNapT+QWIWsorBDK8Xa58N2lUiy6U1Pc2dNYp",
	"9NIUBAOvb+uxux8mrW5oYms3suzYlmBqIVTGSYr5CnUXazJXtg33cqv35E9+nwvVADovyv+kMMfGHDdI",
	"xnfd6cq7VYNdI0zRFOzlqkXq/Si3uVOvTp9TCNusAn75LyEhfnvTexaYhu54dYpsz4lASbQp278/mwQT",
	"EwuvTsfbHKqN07A2UFN1gLdSuUKRj++IMLHnrkkZ0unqKFX3WBfKLgEwWExTh9h/FKFFcfH3EaMiT0En",
	"NIR2Q4uFo/1G37EX+m/0krFE2AIRpcwNT2DP4GvVRQ1dVggJlPVliWgbrzoOFRInCS407DwojvPhBRdu",
	"Ui8X8NTWblFD5C3H4BK40B66vHEkYiHInJrIqI5D8ElufB01OP2bmLfbmtcbTxdvXEI8Ie40WSsNhtzL",
	"XHHF6r3sltBQmXFTatEollHMWTpGs4Rl2WqMcjEdIwGc4GSMMsxxkkASvpf2wWQtITV/UIgjT3JhoRGR",
	"IGPFAWMksMRjRJdpyxXO1u9vMba4z2tu8xlJgiH8p39D6hPKsFy4lyIDmToleLewatX5tD/hFlbaEW0H",
	"axw7Q07oIhWqgb5+m3vHmeGpNI8OavFN5Ze2v1NGy09BqvM47ZKARBiZd4nvkOWyc5xlFSnlST8T3tAt",
	"UjWxiHChEFOQdwAUpXkiSZbUCScGvsTdpgxbH0goVkGHnK+6C1zUjpwF4zZ22wm1Il7Bek7C9Rx1san+",
	"/AvXcFxC52D5vAbO7gLQY+wWqOxi3Tqi+Z6jdQhtqrg3FiIUyN6HWbisib+CLtlvUpZU+XtRUuWsUlLl",
	"uCyp8trW+/qgmHNgsagAaDZ7YeVN3tGqhKujURXkjoYeNh2tHKIdTSwN+oqCm/MfYr8cuIm/iRiVcC91",
	"uW4OEUtToDF271RusMUGvwTibRZ/sP4t011K+1/o8bvavi5CIpRgsumSwcfwaqL2kUpQL5sSfZ0y1M07",
	"UaAaWgwBL8n7s4l9m7frYA6cwz2FpTeqId1hjOoXgSabsjWLch0zyA6HLMERqPu2Tkea2y+7j5+8SJmc",
	"JpjehgweYRNCUItgzlRQWA/6LAYbxQAGlyV0GQrl5z92fRMTmPFnL4iyFpaPWUElZS21boYVVdm8nMp6",
	"hVRaKu7U9Uxm/I2pq50SKG3SVtQkhElfxRWPX/vKr3iLHqrF8rklTaieTtTYkfrE0a1OBkWFXZ+U9mJp",
	"vCJDPNVpb+jSzXn5Sq0kwYM5FAZuQS+n+NyRMPUoVNAfbOm67ZGiJU5eT6btO0S4SXvI5CYcV7D83Jkf",
	"EcgabnnpwCRiuXSj2kM5V66QvMkWyoCjS4jRWyzR3yZXCHNJogTQi2fPX7z89cirTWJjlrXl2JSK/1IW",
	"INSFgtOcErmq/FXdqAhOviwwjZPwk0IFwBCHXzfNsznHMVxW9PRAJXH3HWL04QrZXi6wC3nlEtVnE4Zt",
	"3AW2aazrOCC/Wa9a76o4hUoxFm/i20qgGjsi9dNBx8KGKBZJN8gEwR5fnI28SNnR8pnmggwozsjo1ej5",
	"/uH+c62GyoVmhANd2EJH95pgAuYqMp7Fo1ejNyD1wFfOusrtHUJ3fnZ4aFUAaQfxEtoP/lMYOhtVuk/R",
	"9qfROIdifEXhqntppq47jCVwihMkgC+B2yLXOtPAiQmFEcL+YOORUY3+YebQ98LMelurxLiyxNBlfMxC",
	"gpAnLF5tlwpq/KK8VJVlJM/h2/dbBV2UKFpgOodYrcKL8CroF48RLytkvTj8NRgeM0uIkVMbL+dEA2NX",
	"NDULU1/Pb+PRQWTe73flOoLMru7IE6/dI9K5nKZyMQ+Q3DmgfAQeQjA9Hk6SyoAlzXz8G5TTmGAOB1/x",
	"Wfzt4Ov0LP7WSk3z6D5UCZphjlMwxTn+0TClYwGJ9sMWfZD2SxCq85HkwrktXo2wfhm5ujHGHvEbcrfJ",
	"fQo8IhhFptzokFmna876+UlYqESlyP5u8pGHr2UGY8vKgO95mOP5nMNcaaXauhWT2UyYHfwiEH5CzPvp",
	"ZXfKpAlVf9imNqyD5B3z2VTnOrlErSCgD+Djg68xSYGqc3Mdnj4ls9l/Pb4eB7OTQHISKS3Ikjc8V0Hm",
	"zhmd2ujMZ6mfE0oZ3UtD5UjaAbwobZho52hvigXEu/voWG0/7VAvPEnJSqHAaLI6o8eat8zPJ/sOn3/m",
	"oC2wFiFr2SthL6JBjryadEchrb7rwqCDK5V+rc2v6gdBYuiAwUbHlnB0zv3UoklvlIBcusBzQvUTLxZl",
	"rVqr7Qy88JjJRVMYuJCzOVkCRSVX9aklRUu01C+1PbVwO+UkSVDM7qiWZ11YBzDGDXyHyryvJP52UC9b",
	"1qoHHfsNe+TbpF/AkB/n3PQwG6p7haq4tZ+Kk21zjAYjCAMiFGGPR3zlt1JaLMwNrnbZwVf7kzoHa+Ey",
	"bdfCQO3sJ2eThvx0ebGmFq57Mz5mKSZ0Lzp69vzTaBcxjuZAQYf4FWXz2iAqCNMJWBk6+T933GyfPsV/",
	"/V+2+94/Dvd+xXuzz1+Pfvm2+28Bu8BjcnxH4faQomgpUk9gKR8FtYmSxdtOiJcTIFOGvVcKl+WtkbWw",
	"rbOdxogyf34951itbFEGcSs77w3IAtsAWaarKv+4vecRvG3rwb0mU9sGe60/T/yN/b331oSlKd4ToOBQ",
	"RDcYIBGxDLxyQWwJfEngbrxMxdjkCX8a7e6jU6MU6XqiZatPozatSo87WgvCD7nMcmn56RX6g2RoZ3J1",
	"o6OfrKj8H2cXCPNoQZagBcF9Iu7Rzuv7CBJ0x/jtlLFbcy8yJUwApFG9FDS7LaBaBg6qgKM/SOZZQc1v",
	"ataQ1rqeEFjSeJ9lQO/TxEAg9thsRiKIWZSnQOW+yDjgWGORJvv6/6rUKIzbU0KxRqlpr/Sn/MO8XLzO",
	"AA354i2BDqTARD8kVC4U46i6IL3CxPDKk53HZnP6mqGWj1hoJHz8mqispa2Vefitetob97b49xYP9vF7",
	"WxlgagPTdyIsYI9QoR94JPpNnqkZxIRutO2p6cq9DjMchNodT4dDmIjvJ7u2WfTdtW2d21ox/bPD1sLm",
	"T32Ra77C36ElW27t26wmSEcdHxxEeWN7MkUaJ4lbpnbt2W6rzn158FX/32UDfQNmg/4A+1PD0Tq6xeRh",
	"U1wpqTgjkMS24HBMuMWqUA/UfK+wiEyZPas9vVLjaC3hxrKIHgNzU6VgjPwU4bHTuXQOrXaHj+3LvWNb",
	"LWOMoiz/KPAcTBv7I8ep/SnK8uPlXHc7Xs6VCgL3upiAV9FZQWkJpOFTBzbcZ4kOXLbv4Yb0FqXW+WQb",
	"XhJFyFXi9IlRt3ibMS1gbPWqp5RwGp2NBNz3lWJdEszsDfcGr2bdemj2ABnF7Om3xbuHGW+6QmenBiwi",
	"RShqfJDUqryI0Cauzrw3D/5ERh//kYeAa0Sjos3ARbNB61203+KaR01orOUveFI5zPTDeOGFt0GpqRf7",
	"2qpPNpnrB1EspytfZWhTGl/7TX4eXT+Prn/xo6sjiL9DEw8eXv2RGsjb6k+rk9ej+tsV8zpqw0Tegbl0",
	"7LGs2/PxBmTtBZg/1zHY9rxNgJes2HUUezJ+0PFZS0wSU1fNh8I47MTDuaHMIWjnguLdlj/V8tdekwnJ",
	"EJM6YfOc9AMrT7v2iQ7Mrbwd4wPz4MX/ukx7ruyNtJnvrQI16mKGp1GI/Ti8Fiq+FeC3Gm5xmXQ/QP+u",
	"lzTcGhe2QLUl5hvqY705/7HcqzWquBdH/xW4MVjYIcCN51W/53BuLHhP8WWg/l+lJs9D2bPihHQPBthb",
	"onDv1Ou6JIP4ldlI/wRMkZBa2LNk2aRo2FikdrIw/TJ/lsHD9qOaH0UeADUPCjO5vK2BCq7V48ew16dq",
	"tzUwvq1Y9qg+YBt9WmLaJeayY3WffQfi2HIuOh/i4UHmZWhrwgHHuqpGxtmc20o8D+BLzGXbPcWnfWWn",
	"HfClrnCjw0bal+TStKquTFu+gSkogbk8UPfvPV1utLIu1eQf7Wat3O973bg9ac9mxHDuSl/ywo/KYe+Z",
	"9Ue71xmeiMdU66NAftKNKXqkq6MQoc8bV4urjy9N6I4bwSxWB6tW3z0pj4V6wlTKliC0wq5LycRFeSJv",
	"hDJqSHHlFAvYH41rDH+qZ/CfWxl0yHiTGBgfGJepx3CoRBVoClJ5f/XOnDphTIR6YySUgsRaF9j5ePlO",
	"hxXv7qP3sDTuUCZAv6XHTUk3jtxjFfvoeqErr8UZI1SimIFZfw5aCGIJFZLjOSZUSPdKRJPg6lTsovYW",
	"T8Rimo49WRKoPBOD6tZ7VsHTEPjBJ2hznZonaW3di2fLK7qjXQvRtRhjBDTiq0wWdmZxa6LR0S2sxjre",
	"XAMkXKmmhEU4KXYPwqbiLo50NIUPNMh9dKzjK9RBQSW6+HiN2BL4HScKKtUt47AkLBfJKsDoTUa5yBuM",
	"sv2ct8BzS0+c9bYelwrkdl1cLpdmw2dGcH8XmCIOAYi6YzC97oyjnHLA0ULb3VzBugfq7RxCZ0Lrxqqd",
	"PgcRzrB+MYlUvFY1IiwguhXFkzgZJ0uSwBxsvHySoIKnBdop9LCxewtE/ThjHCIsJPBd+85SYHegK0Ln",
	"CaBEbTw3XaRmN+Go+mo175G2Ex+lx2RpN8+qg32KNlbiad9IAfwTimG9hgVNCwhQVKVWO9eUC9ilsqib",
	"pJGDtv4kmgKNFinmt/vo2Khue15YcU6NJy/joIGP/fJ5YV1GTfF7CcwjarvlLO0rfOLQQxGmESQQ6wKJ",
	"uridSaQzaesa8671LujkF+980IpreMpxvdX1yNerY9lXxQukTBXYIrExw4QXiriz5gR3aIOaj7g3h6yc",
	"q71VMvY2DAYXLEkCQ7bSPgtWHdcXDIGwWNGoXEG1nZTEZVQrr6kS/kWZSaRWQoS2C+aytl+2r2HUZlkr",
	"t/57bdihBhBPEo+dYqJf31bLPzbXCMJRQlIiEdxHAF1X2WPKdNZbZb+7S+029r25nPZu+6pMbygCYb6c",
	"sDTLlaZ7tyDRArHZLGE4VreuBbMxGTPA+mUNzamFpdS8vLpn82VrTIuMdq6fY6Sx6mYLoDhNC88BabMI",
	"kixjCZuvUAycLF11b12ZjvHbhMzkXiC6J6B2M+Gx6wUmvKE2bH+TVKZZPWL9iWGlsivQBAxQ7doMARfk",
	"QXjr9jktFnl7Keu5NCzTprZ0cXjBdO2KrjvzyqbD+Mu+GWs51TKxYt6o1P9IWYSzyrzvj4+RefLEq23d",
	"d4Selsg8Ba8U0zkvYz+zFJmdJaQddkC/PoILTdhCIHoR5RD79BrCLVowHXylOIVvXQqv0bKMyluK9Jqf",
	"SLOsTdjYR9eGm5yGoFaK0BwKrQ+RGTJnhJGOSqoKSZLEmiT6VGK1sftcmaqNyR/BwsFZKt/6ZCwM/0Hf",
	"o6319hDf43rnfr2cKuHvw+XpxiPhXjMoKmNZ1TxYxyBkUQ8QqxhjkA5vl7LUDkrn5UFx2s8IJWLx0Iud",
	"UfMxEubunJnVH8Lj6vbVKwsJjcmSxDlOfJVFuvv+PjKRTrpEv4klMgX5M8dhPZLsMu8PAbORUvq26A/d",
	"GmBomeMxfeGD5GahbF7mdB2hWWGkLVQjqo03nD10jEWX69rY9CvL2beal/nG8RO9NfoDyxrYqgoCz6HR",
	"7f400LbtejXUlqpWGO8Iri7WwLVSIq9/L0dGhYr1rZQISSJX8qKqkf9F+ECYYu776MI+zVR4SVx9kI9n",
	"SDIU2+dyisK5SJIUEAhJUixhiFFADD+2JENzkDVE+uXBjxEr47A2OAfkwPWCs3y+yHIfw1ZWPSdCW1Qd",
	"nmWU8YM9NzIISAdPDkiofafT/Yel1f7Mef2Z87rlnNf39ZI/W4mvt0vUrODRlfraFjI00Z4mb588kkHC",
	"zGOT99awRhxtlxXaEwaty229GKWnWHNDOYQRhTubQ+icyUMWvpSU1RTnbi2ryhCdcnP7uciDFCuX5ump",
	"Vv2rseWsTqtHmSHX3Y9tIY7flfQ/c+l+5tL9l08Df1yhUU8FX/scV1pnU3KYl1a+v9zevupgMFtfdTh8",
	"KtUh1wBuXXXYMt8ZMm6oQRThNX25BeXDaaNHrQBgwWl3vhZN/LSFINnLljoMs/SLBp2ql7o8nSs6qN/R",
	"3VoIOsvKOKZKVQD3ty69oU6Tnu1/Rs1LRDenp38rY1ktX7iFazkKiOl7E8e3oQtu+eDh5x+HB8pY1Cdd",
	"VCXtSR2MtqXtSCGo7atHCqvw32L8LmEVwxd1g7wStEMZujkXOsJP8b0J9StjLnZbGaTkpO3HT8QAxb7X",
	"8f2MKyhbuKQijQ+Wagt2VoCxLdVeffxgKDXLRek9C+Xk+eKm6yTUDfMsYTjeQli4N1rvJswDpLzIq6Tc",
	"dgbP0PqN9TydDdN0nnzF/YXs3Kqqdesu/GgWsCUv58XR82aX30kCSDKGEszngHZSfI9+eXF+svtAXUoD",
	"olGTmE9xknRu1wG1mozm7lds+vHrJzUV1seooeRVThpyVWrWUCpeUOpIzrZNHnOnmCn0E16hbWI++8E7",
	"rY8dLQNtvexgi4tFfo16UYYH16wa9bOk008z1M+STj9KSafHcTnVSzoNEsThKgX1IhpTLKPFnjGh7Onn",
	"cZ2sDt+GTlR739h1c/666PU4VyNvymKq9S1RtQdJ3ECPZT16+MprtC14XqhFsUZaUhhdN4HyfdBtMMXw",
	"Cl+OB+p1vv6Fqm5tfeH6q25tcwP3199ya1RU4fpXqYn1OCvTXRNr+0tz8FX/P9jrqwn0JmHqVtNbOVY3",
	"rkRIVv0IeuofJhrKoekh2MsqiOvaCGsJ6I0ZxNRhQNgwhuEFxTAbS9dB/iKNpzE5fY/FfiyXkUProWe1",
	"QfuHPaePY12migdY53FO5/6ie6GLZB9z/ayL12FXeeLaeJseQoOkzQ/EFo9Q/6ICrkH7ofKnRoLHczc/",
	"CpdZv3Nt7NIEvm25NLQeo9NK16jK+LNkYi8L/SDFEocJsNrTbmoyPbtZ+5wno1ejA5yRg+WzkVoe2+9r",
	"x3P2OhdTl/VKMcVzSNXSFTxhHjEPPcdWeX1K1wYK9Z9U3g0PbHxrKPdyHMt6KY1hdIGyr/32f8TBJFV7",
	"Q/hW9tbaoshuTfTPHFRLhCPOhKkyZu2u3pBNq1jP/jOhLCE6vXGR3I1M4cDDm56jo1yo6tugjXiBxhuJ",
	"ZuGtffeguo3KYX2GCwEHmeJdzxeckBlEqygBPbxxngbwLT1OgWc0GzV7wqzlV2wah1k87Hdwy2fdDt8+",
	"f/t/AQAA///YmSG7nhwBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
