// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"time"

	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Defines values for AgentModeRequestMode.
const (
	Connected    AgentModeRequestMode = "connected"
	Disconnected AgentModeRequestMode = "disconnected"
)

// Defines values for AgentStatusConsoleConnectionStatus.
const (
	ConsoleConnectionStatusConnected    AgentStatusConsoleConnectionStatus = "connected"
	ConsoleConnectionStatusDisconnected AgentStatusConsoleConnectionStatus = "disconnected"
)

// Defines values for AgentStatusMode.
const (
	AgentStatusModeConnected    AgentStatusMode = "connected"
	AgentStatusModeDisconnected AgentStatusMode = "disconnected"
)

// Defines values for CollectorStatusStatus.
const (
	CollectorStatusStatusCollected  CollectorStatusStatus = "collected"
	CollectorStatusStatusCollecting CollectorStatusStatus = "collecting"
	CollectorStatusStatusConnecting CollectorStatusStatus = "connecting"
	CollectorStatusStatusError      CollectorStatusStatus = "error"
	CollectorStatusStatusParsing    CollectorStatusStatus = "parsing"
)

// Defines values for InspectionStatusState.
const (
	InspectionStatusStateCanceled  InspectionStatusState = "canceled"
	InspectionStatusStateCompleted InspectionStatusState = "completed"
	InspectionStatusStateError     InspectionStatusState = "error"
	InspectionStatusStatePending   InspectionStatusState = "pending"
	InspectionStatusStateRunning   InspectionStatusState = "running"
)

// Defines values for VirtualMachineIssueCategory.
const (
	VirtualMachineIssueCategoryAdvisory    VirtualMachineIssueCategory = "Advisory"
	VirtualMachineIssueCategoryCritical    VirtualMachineIssueCategory = "Critical"
	VirtualMachineIssueCategoryError       VirtualMachineIssueCategory = "Error"
	VirtualMachineIssueCategoryInformation VirtualMachineIssueCategory = "Information"
	VirtualMachineIssueCategoryOther       VirtualMachineIssueCategory = "Other"
	VirtualMachineIssueCategoryWarning     VirtualMachineIssueCategory = "Warning"
)

// AgentModeRequest defines model for AgentModeRequest.
type AgentModeRequest struct {
	Mode AgentModeRequestMode `binding:"required,oneof=connected disconnected" json:"mode"`
}

// AgentModeRequestMode defines model for AgentModeRequest.Mode.
type AgentModeRequestMode string

// AgentStatus defines model for AgentStatus.
type AgentStatus struct {
	ConsoleConnection struct {
		// Error Connection error description
		Error *string `json:"error,omitempty"`

		// Status Current console connection status
		Status AgentStatusConsoleConnectionStatus `json:"status"`
	} `json:"consoleConnection"`

	// Mode Target mode for the agent
	Mode AgentStatusMode `json:"mode"`
}

// AgentStatusConsoleConnectionStatus Current console connection status
type AgentStatusConsoleConnectionStatus string

// AgentStatusMode Target mode for the agent
type AgentStatusMode string

// ApplicationListResponse defines model for ApplicationListResponse.
type ApplicationListResponse struct {
	Applications []ApplicationOverview `json:"applications"`
}

// ApplicationOverview defines model for ApplicationOverview.
type ApplicationOverview struct {
	// Description Application description
	Description string `json:"description"`

	// Name Application name
	Name string `json:"name"`

	// VmCount Number of VMs running this application
	VmCount int             `json:"vmCount"`
	Vms     []ApplicationVM `json:"vms"`
}

// ApplicationVM defines model for ApplicationVM.
type ApplicationVM struct {
	// Id VM ID
	Id string `json:"id"`

	// Name VM name
	Name string `json:"name"`
}

// BatchUpdateExclusionRequest defines model for BatchUpdateExclusionRequest.
type BatchUpdateExclusionRequest struct {
	// MigrationExcluded Exclusion state to set for all VMs
	MigrationExcluded bool `json:"migrationExcluded"`

	// VmIds VM IDs to update
	VmIds []string `binding:"required,min=1,dive,required" json:"vmIds"`
}

// CapabilityStatus defines model for CapabilityStatus.
type CapabilityStatus struct {
	Capabilities struct {
		Collector  OperationCapability `json:"collector"`
		Forecaster OperationCapability `json:"forecaster"`
		Inspector  OperationCapability `json:"inspector"`
	} `json:"capabilities"`
}

// Collection defines model for Collection.
type Collection struct {
	// CreatedAt When the collection was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Collection identifier
	Id string `json:"id"`

	// Name Collection name
	Name string `json:"name"`
}

// CollectionListResponse defines model for CollectionListResponse.
type CollectionListResponse struct {
	Collections []Collection `json:"collections"`
}

// CollectorListResponse defines model for CollectorListResponse.
type CollectorListResponse struct {
	Collectors []CollectorStatus `json:"collectors"`
}

// CollectorStatus defines model for CollectorStatus.
type CollectorStatus struct {
	// Error Error message when status is error
	Error *string `json:"error,omitempty"`

	// Id Collector identifier
	Id     string                `json:"id"`
	Status CollectorStatusStatus `json:"status"`
}

// CollectorStatusStatus defines model for CollectorStatus.Status.
type CollectorStatusStatus string

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string   `binding:"omitempty,max=500" json:"description,omitempty"`
	Filter      string    `binding:"required,min=1" json:"filter"`
	Name        string    `binding:"required,min=1,max=100" json:"name"`
	Tags        *[]string `binding:"omitempty,dive,tag_format" json:"tags,omitempty"`
}

// CredentialStatus defines model for CredentialStatus.
type CredentialStatus struct {
	// Url vCenter URL the credentials belong to
	Url string `json:"url"`

	// Username vCenter username
	Username string `json:"username"`

	// Valid Whether credentials are stored for the returned URL.
	Valid bool `json:"valid"`
}

// DeleteLabelGloballyResponse defines model for DeleteLabelGloballyResponse.
type DeleteLabelGloballyResponse struct {
	// Affected Number of VMs that had the label removed
	Affected int `json:"affected"`

	// Label The label that was removed
	Label string `json:"label"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Optional group description
	Description *string `json:"description,omitempty"`

	// Filter Filter expression (pkg/filter DSL)
	Filter string `json:"filter"`

	// Id Unique group identifier
	Id string `json:"id"`

	// Name Group display name
	Name string `json:"name"`

	// Tags Tags applied to matching VirtualMachines
	Tags      *[]string  `json:"tags,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Groups    []Group `json:"groups"`
	Page      int     `json:"page"`
	PageCount int     `json:"pageCount"`
	Total     int     `json:"total"`
}

// GroupResponse defines model for GroupResponse.
type GroupResponse struct {
	Group     Group            `json:"group"`
	Page      int              `json:"page"`
	PageCount int              `json:"pageCount"`
	Total     int              `json:"total"`
	Vms       []VirtualMachine `json:"vms"`
}

// GuestNetwork defines model for GuestNetwork.
type GuestNetwork struct {
	// Device Network device name inside the guest
	Device *string `json:"device,omitempty"`

	// Ip IP address
	Ip *string `json:"ip,omitempty"`

	// Mac MAC address as seen by the guest
	Mac *string `json:"mac,omitempty"`

	// Network Network name from the guest
	Network *string `json:"network,omitempty"`

	// PrefixLength Network prefix length (CIDR)
	PrefixLength *int32 `json:"prefixLength,omitempty"`
}

// InspectionStatus defines model for InspectionStatus.
type InspectionStatus struct {
	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// State Current inspection state
	State InspectionStatusState `json:"state"`
}

// InspectionStatusState Current inspection state
type InspectionStatusState string

// Inventory defines model for Inventory.
type Inventory struct {
	Inventory externalRef0.UpdateInventory `json:"inventory"`
}

// OperationCapability defines model for OperationCapability.
type OperationCapability struct {
	// Enabled Whether stored credentials have sufficient privileges
	Enabled bool `json:"enabled"`

	// MissingPrivileges Specific vSphere privileges that are missing
	MissingPrivileges *[]string `json:"missingPrivileges,omitempty"`
}

// RightsizingClusterResponse defines model for RightsizingClusterResponse.
type RightsizingClusterResponse struct {
	Cluster  RightsizingClusterUtilization `json:"cluster"`
	ReportId string                        `json:"report_id"`
}

// RightsizingClusterUtilization defines model for RightsizingClusterUtilization.
type RightsizingClusterUtilization struct {
	ClusterId                string  `json:"cluster_id"`
	ClusterName              string  `json:"cluster_name"`
	Confidence               float64 `json:"confidence"`
	CpuAvg                   float64 `json:"cpu_avg"`
	CpuMax                   float64 `json:"cpu_max"`
	CpuP95                   float64 `json:"cpu_p95"`
	Disk                     float64 `json:"disk"`
	MemAvg                   float64 `json:"mem_avg"`
	MemMax                   float64 `json:"mem_max"`
	MemP95                   float64 `json:"mem_p95"`
	TotalProvisionedCpus     int     `json:"total_provisioned_cpus"`
	TotalProvisionedDiskKb   float64 `json:"total_provisioned_disk_kb"`
	TotalProvisionedMemoryMb int     `json:"total_provisioned_memory_mb"`
	VmCount                  int     `json:"vm_count"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	Description *string   `binding:"omitempty,max=500" json:"description,omitempty"`
	Filter      *string   `binding:"omitempty,min=1" json:"filter,omitempty"`
	Name        *string   `binding:"omitempty,min=1,max=100" json:"name,omitempty"`
	Tags        *[]string `binding:"omitempty,dive,tag_format" json:"tags,omitempty"`
}

// UpdateLabelVMsRequest defines model for UpdateLabelVMsRequest.
type UpdateLabelVMsRequest struct {
	// Add VMs to add the label to
	Add *[]string `binding:"omitempty,dive,required" json:"add,omitempty"`

	// Remove VMs to remove the label from
	Remove *[]string `binding:"omitempty,dive,required" json:"remove,omitempty"`
}

// VMFilterOptionsResponse defines model for VMFilterOptionsResponse.
type VMFilterOptionsResponse struct {
	// Applications Distinct detected application names
	Applications []string `json:"applications"`

	// Clusters Distinct cluster names
	Clusters []string `json:"clusters"`

	// ConcernCategories Distinct concern categories
	ConcernCategories []string `json:"concernCategories"`

	// ConcernLabels Distinct concern labels
	ConcernLabels []string `json:"concernLabels"`

	// Datacenters Distinct datacenter names
	Datacenters []string `json:"datacenters"`
}

// VMLabelsResponse defines model for VMLabelsResponse.
type VMLabelsResponse struct {
	// Counts Number of VMs with each label (same order as labels array)
	Counts []int `json:"counts"`

	// Labels Distinct labels currently in use
	Labels []string `json:"labels"`
}

// VcenterCredentials defines model for VcenterCredentials.
type VcenterCredentials struct {
	// Cacert PEM-encoded CA certificate bundle for verifying the vCenter TLS certificate. Mutually exclusive with skipTls.
	Cacert   *string `binding:"omitempty" json:"cacert,omitempty"`
	Password string  `binding:"required,min=1" json:"password"`

	// SkipTls When true, TLS certificate verification is skipped. Must not be set to true alongside cacert — that combination returns 400. When omitted: if cacert is absent the connection skips TLS verification (backwards compatibility); if cacert is provided the connection verifies TLS using that certificate — skipTls need not be sent.
	SkipTls *bool `json:"skipTls,omitempty"`

	// Url vCenter URL
	Url      string `binding:"required,url" json:"url"`
	Username string `binding:"required,min=1" json:"username"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// GitCommit Git commit SHA
	GitCommit string `json:"gitCommit"`

	// UiGitCommit UI git commit SHA
	UiGitCommit string `json:"uiGitCommit"`

	// Version Agent version
	Version string `json:"version"`
}

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// Cluster Cluster name
	Cluster string `json:"cluster"`

	// Datacenter Datacenter name
	Datacenter string `json:"datacenter"`

	// DiskSize Total disk size in MB
	DiskSize int64 `json:"diskSize"`

	// Id VirtualMachine ID in vCenter
	Id string `json:"id"`

	// InspectionConcernCount Number of inspection concerns for the latest persisted result
	InspectionConcernCount *int              `json:"inspectionConcernCount,omitempty"`
	InspectionStatus       *InspectionStatus `json:"inspectionStatus,omitempty"`

	// IssueCount Number of issues found for this VirtualMachine
	IssueCount int `json:"issueCount"`

	// Memory Memory size in MB
	Memory int64 `json:"memory"`

	// Migratable True if the VirtualMachine is migratable for MTV
	Migratable *bool `json:"migratable,omitempty"`

	// Name VirtualMachine name
	Name string `json:"name"`

	// Tags Tags aggregated from matching groups
	Tags *[]string `json:"tags,omitempty"`

	// Template True if the VirtualMachine is a template
	Template *bool `json:"template,omitempty"`

	// VCenterID Identifier of the vCenter this VirtualMachine belongs to
	VCenterID string `json:"vCenterID"`

	// VCenterState vCenter state (e.g., poweredOn, poweredOff, suspended)
	VCenterState string `json:"vCenterState"`
}

// VirtualMachineDetail defines model for VirtualMachineDetail.
type VirtualMachineDetail struct {
	// Cluster Cluster name
	Cluster *string `json:"cluster,omitempty"`

	// ConnectionState Connection state (connected, disconnected, orphaned, inaccessible)
	ConnectionState string `json:"connectionState"`

	// CoresPerSocket CPU cores per virtual socket
	CoresPerSocket int32 `json:"coresPerSocket"`

	// CpuAffinity Physical CPU IDs the VirtualMachine is pinned to
	CpuAffinity *[]int32 `json:"cpuAffinity,omitempty"`

	// CpuCount Total virtual CPUs
	CpuCount int32 `json:"cpuCount"`

	// Datacenter Datacenter name
	Datacenter *string                 `json:"datacenter,omitempty"`
	Devices    *[]VirtualMachineDevice `json:"devices,omitempty"`
	Disks      []VirtualMachineDisk    `json:"disks"`

	// FaultToleranceEnabled Whether Fault Tolerance is enabled
	FaultToleranceEnabled *bool `json:"faultToleranceEnabled,omitempty"`

	// Firmware Firmware type (bios or efi)
	Firmware *string `json:"firmware,omitempty"`

	// Folder Inventory folder reference
	Folder *string `json:"folder,omitempty"`

	// GuestId VMware guest OS identifier
	GuestId *string `json:"guestId,omitempty"`

	// GuestName Guest OS full name
	GuestName     *string         `json:"guestName,omitempty"`
	GuestNetworks *[]GuestNetwork `json:"guestNetworks,omitempty"`

	// Host ESXi host reference
	Host *string `json:"host,omitempty"`

	// HostName Guest hostname
	HostName *string `json:"hostName,omitempty"`

	// Id Unique identifier for the VirtualMachine in vCenter
	Id string `json:"id"`

	// Inspection VirtualMachines Inspection results
	Inspection *VirtualMachineInspectionResults `json:"inspection,omitempty"`

	// IpAddress Guest primary IP address
	IpAddress *string                `json:"ipAddress,omitempty"`
	Issues    *[]VirtualMachineIssue `json:"issues,omitempty"`

	// MemoryMB Memory in megabytes
	MemoryMB int32 `json:"memoryMB"`

	// Migratable Whether the VirtualMachine can be migrated
	Migratable *bool `json:"migratable,omitempty"`

	// Name Display name of the VirtualMachine
	Name string `json:"name"`

	// NestedHVEnabled Whether nested virtualization is enabled
	NestedHVEnabled *bool               `json:"nestedHVEnabled,omitempty"`
	Nics            []VirtualMachineNIC `json:"nics"`

	// PowerState Current power state (poweredOn, poweredOff, suspended)
	PowerState string `json:"powerState"`

	// StorageUsed Storage consumed in bytes
	StorageUsed *int64 `json:"storageUsed,omitempty"`

	// Template Whether the VirtualMachine is a template
	Template *bool `json:"template,omitempty"`

	// ToolsRunningStatus Whether VMware Tools is running
	ToolsRunningStatus *string `json:"toolsRunningStatus,omitempty"`

	// ToolsStatus VMware Tools installation status
	ToolsStatus *string `json:"toolsStatus,omitempty"`

	// Uuid Universally unique identifier assigned by vCenter
	Uuid *string `json:"uuid,omitempty"`

	// VCenterID Identifier of the vCenter this VirtualMachine belongs to
	VCenterID string `json:"vCenterID"`
}

// VirtualMachineDevice defines model for VirtualMachineDevice.
type VirtualMachineDevice struct {
	// Kind Device type (cdrom, floppy, usb, serial, parallel)
	Kind *string `json:"kind,omitempty"`
}

// VirtualMachineDisk defines model for VirtualMachineDisk.
type VirtualMachineDisk struct {
	// Bus Bus type (scsi, ide, sata, nvme)
	Bus *string `json:"bus,omitempty"`

	// Capacity Disk capacity in bytes
	Capacity *int64 `json:"capacity,omitempty"`

	// File VMDK file path in the datastore
	File *string `json:"file,omitempty"`

	// Key Unique disk key within the VirtualMachine
	Key *int32 `json:"key,omitempty"`

	// Mode Disk mode (persistent, independent_persistent, independent_nonpersistent)
	Mode *string `json:"mode,omitempty"`

	// Rdm Whether this is a Raw Device Mapping
	Rdm *bool `json:"rdm,omitempty"`

	// Shared Whether the disk is shared between multiple VirtualMachines
	Shared *bool `json:"shared,omitempty"`
}

// VirtualMachineInspectionConcern defines model for VirtualMachineInspectionConcern.
type VirtualMachineInspectionConcern struct {
	Category string `json:"category"`

	// Label Short label identifying the concern
	Label   string `json:"label"`
	Message string `json:"message"`
}

// VirtualMachineInspectionResults VirtualMachines Inspection results
type VirtualMachineInspectionResults struct {
	Concerns *[]VirtualMachineInspectionConcern `json:"concerns,omitempty"`
}

// VirtualMachineIssue defines model for VirtualMachineIssue.
type VirtualMachineIssue struct {
	Category VirtualMachineIssueCategory `json:"category"`

	// Description Detailed description with context and recommendations
	Description string `json:"description"`

	// Label Short label
	Label string `json:"label"`
}

// VirtualMachineIssueCategory defines model for VirtualMachineIssue.Category.
type VirtualMachineIssueCategory string

// VirtualMachineListResponse defines model for VirtualMachineListResponse.
type VirtualMachineListResponse struct {
	// Page Current page number
	Page int `json:"page"`

	// PageCount Total number of pages
	PageCount int `json:"pageCount"`

	// Total Total number of VirtualMachines matching the filter
	Total           int              `json:"total"`
	VirtualMachines []VirtualMachine `json:"virtualMachines"`
}

// VirtualMachineNIC defines model for VirtualMachineNIC.
type VirtualMachineNIC struct {
	// Index NIC index within the VirtualMachine
	Index *int `json:"index,omitempty"`

	// Mac MAC address
	Mac *string `json:"mac,omitempty"`

	// Network Network reference
	Network *string `json:"network,omitempty"`
}

// VirtualMachineUpdateRequest defines model for VirtualMachineUpdateRequest.
type VirtualMachineUpdateRequest struct {
	// Labels User-defined labels (replaces existing labels)
	Labels *[]string `binding:"omitempty,dive,notblank,min=1,max=100" json:"labels,omitempty"`

	// MigrationExcluded Whether to exclude this VM from migration
	MigrationExcluded *bool `binding:"omitempty" json:"migrationExcluded,omitempty"`
}

// VmUtilizationDetails defines model for VmUtilizationDetails.
type VmUtilizationDetails struct {
	Confidence          float64 `json:"confidence"`
	CpuAvg              float64 `json:"cpu_avg"`
	CpuLatest           float64 `json:"cpu_latest"`
	CpuMax              float64 `json:"cpu_max"`
	CpuP95              float64 `json:"cpu_p95"`
	Disk                float64 `json:"disk"`
	MemAvg              float64 `json:"mem_avg"`
	MemLatest           float64 `json:"mem_latest"`
	MemMax              float64 `json:"mem_max"`
	MemP95              float64 `json:"mem_p95"`
	Moid                string  `json:"moid"`
	ProvisionedCpus     int     `json:"provisioned_cpus"`
	ProvisionedDiskKb   float64 `json:"provisioned_disk_kb"`
	ProvisionedMemoryMb int     `json:"provisioned_memory_mb"`
	VmName              string  `json:"vm_name"`
}

// ExportCollectionParams defines parameters for ExportCollection.
type ExportCollectionParams struct {
	// Scope Comma-separated export scopes (e.g., "overview,vms,groups"). Defaults to "overview".
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// ByName Filter groups by name (case-insensitive substring match)
	ByName *string `form:"byName,omitempty" json:"byName,omitempty"`

	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of groups per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetGroupParams defines parameters for GetGroup.
type GetGroupParams struct {
	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListVirtualMachinesParams defines parameters for ListVirtualMachines.
type ListVirtualMachinesParams struct {
	// ByExpression Filter by expression
	ByExpression *string `form:"byExpression,omitempty" json:"byExpression,omitempty"`

	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SetAgentModeJSONRequestBody defines body for SetAgentMode for application/json ContentType.
type SetAgentModeJSONRequestBody = AgentModeRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// BatchUpdateVMExclusionJSONRequestBody defines body for BatchUpdateVMExclusion for application/json ContentType.
type BatchUpdateVMExclusionJSONRequestBody = BatchUpdateExclusionRequest

// UpdateLabelVMsJSONRequestBody defines body for UpdateLabelVMs for application/json ContentType.
type UpdateLabelVMsJSONRequestBody = UpdateLabelVMsRequest

// UpdateVirtualMachineJSONRequestBody defines body for UpdateVirtualMachine for application/json ContentType.
type UpdateVirtualMachineJSONRequestBody = VirtualMachineUpdateRequest

// PutCredentialsJSONRequestBody defines body for PutCredentials for application/json ContentType.
type PutCredentialsJSONRequestBody = VcenterCredentials
